### ISSUE TITLE
[UC] UC-01_basic acquisition

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#1]
1. Instrument scientist starts detector manually/using epics/whatever
  - beamline scientist physically turns on detectors, motors, e.t.c
2. User runs icollection
  - icollection loads conda environment and load ipython profile
  - basic / default beamline configuration is set up here 
3. User starts detector continuous acquisition mode
  - (optional) user turns on continuous acquisition mode manually
  - software calls 'pe1c', an AreaDetector class with continuous acquisition mode plugged in.
    - pe1c yells if area detector is not in continuous acquisition mode (built-in logic coded by software team)
4. Software verifies that detector is running
  - pe1c yells if detector is not "staged" ( built-in logic coded by software team)
5. User executes a scan of 1 second using xpdAcq (preferrably) or bluesky
  - new bluesky syntax 
6. User user retrieves the scan using db
  - dataBroker syntax
7. User visualizes the scan
  - plotting

TODO:
  1. check the maximum stable frame rate and maximum buffer tiff squashing can take
  2. check the maximum frames that can be saved successfully into filesote and dataBroker
  3. learn new area detector attributes and new bluesky syntax
  4. if possible, test motor scan with Dan

**Comment by sbillinge** [comment]
Closing, I don't think this is an issue, just a jot-down of the workflow that we were wanting.
