### ISSUE TITLE
[bug] export directory doesn't exist problem

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#117]
During experiment, extra copies of tiffs are passed to `~/pe1_data/year/month/day`. If this directory doesn't exist, that would raise an issue and stop the scan. This writing behavior is done by tiff exporting mechanism at the beamtime. We should be able to solve this issue inside exporting mechanism.

**Comment by chiahaoliu** [comment]
Update. Local tiffs might be the real data `filestore` is looking at, in this case writing behavior should be driven at higher level, like `bluesky` or `ophyd`. I need to understand entire exporting mechanism behind before addressing problems.

**Comment by sbillinge** [comment]
I think these tiffs are written by areaDetector or sthg, so we should work
with software team on this.

A workaround is to pre create all the directories.  If we know the start
and end time of a beamtime we could also create those directories (and a
few extras to be on the safe side) during _start_beamtime sequence.

But really this should not be our responsibility and I don't really want to
take responsibility for it.

On Sunday, March 6, 2016, Timothy Liu <notifications@github.com> wrote:

> During experiment, extra copies of tiffs are passed to
> ~/pe1_data/year/month/day. If this directory doesn't exist, that would
> raise an issue and stop the scan. This writing behavior is done by tiff
> exporting mechanism at the beamtime. We should be able to solve this issue
> inside exporting mechanism.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/117>.
>


-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
Get that. I will make a reservation with Tom.

**Comment by chiahaoliu** [comment]
This problem has been solved via software team. Export directories are pre-created by software team with scripts. Probably the most appropriate solution.
