### ISSUE TITLE
Make sure resume() on run engine work

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#118]
In general, we would suspend run engine when beamdump or unwanted experiment situation happens. `xpdRE.resume()` should resume paused scan currently hooked to `xpdRE`. But we need to test, as the scan might be sent to run engine by running a script `run -i <script_name>.py` inside ipython session so we need to make sure `xpdRE.resume()` works across entire ipython session.

**Comment by sbillinge** [comment]
@chiahaoliu please don't work on this till we decide on the new design

**Comment by chiahaoliu** [comment]
:+1:

**Comment by sbillinge** [comment]
need to test different ways of dealing with this.  It may not be easy to fix.

**Comment by chiahaoliu** [comment]
Note on 20160322:
```
prun()
<Ctrl + c>
xpdRE.resume()
```
works (for resuming) but it fails to open fast shutter.

**Comment by sbillinge** [comment]
did you put the logic in for catching that keyboard interrupt?

inside get_light_image:
```
xpdRE('pe1c',myscan)     # or whatever is the syntax
while glbl.detector.state == paused:
     userinp = input('Run engine exited in paused state, presumably due to keyboard interrupt.  Type r to resume the scan where you left off, or any other key to abort the scan.')
    if userinp == 'r':
        xpdRE.resume()
    else:
        xpdRE.abort()
```
btw, I am not sure about the syntax for detecting the state of pe1c, but you get the idea.

**Comment by chiahaoliu** [comment]
Yes, that works! I tested with Tramp, time series and count, all worked out. I ended up leaving user input to be blank i.e. `userinp = input()` since bluesky automatically pops out instruction like
```
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

resume()  --> will resume the scan
 abort()  --> will kill the scan with an 'aborted' state to indicate
              the scan was interrupted
  stop()  --> will kill the scan with a 'finished' state to indicate
              the scan stopped normally

Pro Tip: Next time, if you want to abort, tap Ctrl+C twice quickly.
```
I then make conditional statement be aligned instruction: `if userinp == 'resume()'` to avoid confusion. 

This wrapper doesn't cancel all scans in script as expected. The reason is after exiting out one `prun`, there are several waiting in line.

**Comment by sbillinge** [comment]
This is awesome!  I *love* your clever workaround to have the software collect resume().  This is really nice!

I think for the other problem, we could either just put a ``sys.exit`` after the ``xpdRE.abort()`` or we could ask a question: 
```
input('run aborted.  Do you want to continue with subsequent scans or start over?')
```
and then either ``sys.exit()`` or not depending on the response.

This may also be too confusing for people.  Abort is abort really, so just puting ``sys.exit()`` after ``xpdRE.abort()`` is probably best.

**Comment by chiahaoliu** [comment]
Yes, sounds like a good plan. I didn't have chance to do it before I left but I will add it in next visit.

**Comment by tacaswell** [comment]
This is a lot of (brittle) work to avoid just writing custom plans.

**Comment by sbillinge** [comment]
it is hard for me to come up with a way for the custom plans to satisfy our use-cases but we can talk about it.  

One thing I thought about which looks like it could be a good workflow would be to have a third window open that runs scans, then (collection) is used to create scans and queue them, (analysis) is used for interacting with collected data, but a third window (I dunno, (runscans)) just runs the pre-queued scans.  Even then, there would have to be some kind of function that is popping scans off the queue and running them, so even this workflow has ``RE()`` wrapped in another function.

I don't think it is "a lot of work" (brittle maybe) to put a 6-line while statement after RE.  It is about 6 lines worth of work.  And it leverages all the wonderful work done in RE to have robust pausing, resuming and aborting by making it available to the user even from inside helper functions.

**Comment by tacaswell** [comment]
See #159

It sound like you want to have a damon process which is doing

```python
def master_plan():
    while True:
        plan = get_next_queued_plan()
        yield from plan

RE(master_plan())
```

**Comment by chiahaoliu** [comment]
This functionality added and working in the brittle way that Tom doesn't like, but functionality is good and tested for v0.3.  We may revisit later if there is a new behavior on this from bluesky updates.
