### ISSUE TITLE
[bug] Make yamify_dark function to check if _dark_scan_list.yaml exist

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#124]
So far program relies on `icollection` to initiate `dark_scan_list` and yamify it to build up dark bank. Bug pops out if there is no `icollection` being run after `_end_beamtime` (i.e. exit out ipython and renter ipython after `_end_beatime`). 

Not sure if we expect instrument scientist to exit out current ipython session and reenter before next user, but this error can be avoid by adding logic into `_yamify_dark`

**Comment by sbillinge** [comment]
No, this is a bug, not wanted behavior.

On Wednesday, March 9, 2016, Timothy Liu <notifications@github.com> wrote:

> So far program relies on icollection to initiate dark_scan_list and
> yamify it to build up dark bank. Bug pops out if there is no icollection
> being run after _end_beamtime (i.e. exit out ipython and renter ipython
> after _end_beatime).
>
> Not sure if we expect instrument scientist to exit out current ipython
> session and reenter before next user, but this error can be avoid by adding
> logic into _yamify_dark
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/124>.
>


-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by sbillinge** [comment]
@chiahaoliu please check if we can close this issue

**Comment by chiahaoliu** [comment]
this is fixed in PR. Close.
