### ISSUE TITLE
Make dark() as a special function

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#130]
As discussed with Simon, we should make `dark()` a special functions that 1) only does `Count` with the same count time as light image 2) doesn't use `LiveTable`

**Comment by sbillinge** [comment]
:+:

On Thursday, March 10, 2016, Timothy Liu <notifications@github.com> wrote:

> As discussed with Simon, we should make dark() a special functions that
> 1) only does Count with the same count time as light image 2) doesn't use
> LiveTable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/130>.
>


-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
This logic is included in current version from PR #156. Closed.
