### ISSUE TITLE
move sleep(2.5) out of prun?

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#149]
and put is somewhere more relevant?  If it is an issue about the shutter, shouldn't we put it in the shutter logic, for example?

I know that we want to remove it in the end, but even for now, it will be easier to extend the code if it is in a more appropriate place.  Maybe ``prun`` is best, but I am not so sure about that.

**Comment by chiahaoliu** [comment]
Fixed in PR #154, now sleep is moved into `_open_shutter` and  `_close_shutter`. Close issue.
