### ISSUE TITLE
[bug] glbl import problem found at XPD

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#157]
Current `glbl` import structure doesn't work at XPD. Here is the error report:
```
---> 21 from xpdacq.glbl import glbl
     22 from xpdacq.mock_objects import mock_shutter, mock_livetable
     23 from xpdacq.beamtimeSetup import _start_beamtime, _end_beamtime

/home/xf28id1/xpdAcq/xpdacq/glbl.py in <module>()
     61         yaml.dump(dummy_config,fo)
     62 
---> 63 class glbl():
     64     beamline_host_name = BEAMLINE_HOST_NAME
     65     base = BASE_DIR

/home/xf28id1/xpdAcq/xpdacq/glbl.py in glbl()
    125         verify_files_saved = verifyFiles
    126         # real collection objects
--> 127         area_det = pe1c
    128         temp_controller = cs700
    129         shutter = shctl1
```

**Comment by sbillinge** [comment]
Do we have to add this one line (or few lines) back into ``999-load.py``?

maybe all of:
```
area_det = pe1c
temp_controller = cs700
shutter = shctl1
```

**Comment by chiahaoliu** [comment]
Yes, that is the solution I am using now. I don't know if that is preferable in long term tho.

**Comment by sbillinge** [comment]
Yes, that is a fine long-term solution.  As long as we have a solution that works at XPD, for simulation environment and for unit-tests we are good.  I think this will as we only have to find the real pe1c at xpd.

**Comment by chiahaoliu** [comment]
Solution mentioned in this conversation is used and seem to be a good one. Close.
