### ISSUE TITLE
reduce typing for prun etc.

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#172]
@chiahaoliu I promised this at the last beamtime.  It will also need to be documented.

we hand prun() a sample object and  scanPlan object by

``prun(bt.get(4),bt.get(6))``

Let's still allow this behavior, but build a little parser program so that you could alternatively type

``prun(4,6)`` to get the same behavior.  Here, if ``prun`` detects integers it assumes they are list positions and runs ``bt.get(#)``.

Humans also remember names better than indices sometimes so we could allow

``prun('myNi','ct10.3s')``.  If prun detects a string, it tries to match it to a sample object name and a scanPlan object name and gets that.

Of course we want the same behavior in ``calibration()`` and ``background()`` etc., so let's write a little private function that does it and reuse that in the different places.  Alternatively, less work probably, we could just pass the arguments through directly to ``unpack_and_run()`` and interpret them in there.

**Comment by chiahaoliu** [comment]
Yes, I think that is a good idea. I am thinking to apply this parser to ``Scan`` level since the first step of every run function is to instantiate ``scan = Scan(sample, scanplan)``. Does it sound reasonable?

**Comment by sbillinge** [comment]
Without looking at the code I am not sure, but it sounds reasonable.

On Thursday, April 21, 2016, Timothy Liu <notifications@github.com> wrote:

> Yes, I think that is a good idea. I am thinking to apply this parser to
> Scan level since the first step of every run function is to instantiate scan
> = Scan(sample, scanplan). Does it sound reasonable?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/172#issuecomment-212957049>
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by CJ-Wright** [comment]
Can I close this now that #177 is merged?
