### ISSUE TITLE
[user_feedback] 2016.04.22_documentation

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#175]
The is a mix of James feedback and my note on problems he encountered while going through entire workflow based documentation on ``xpdacq.github.io``
**Missing documentation**
  1. we need more detailed instruction on how to open terminal at XPD computer (if no terminal is already open, it is pretty hard to find)
  2. `/home` is actually `/xf28id1/home` on XPD so we need to tell user about it.
  3. Alternative solution to activate conda environment for beamline scientist/user when conda itself is not even correctly configured, i.e. conda can't properly find ``collection`` environment and ``icollection`` hence everything breaks ( it happens today...)

**Userfeedback**
  1. ``QuickStart`` is very easy to read but it would be better to provide code block example at each step and condense explanation to philothophy behaind them. We can just leave a link to full documetation for people who are interested in full explanation.

**Documents need to be refined**
  1. highlight the line of openning *a new terminal* when openning ``getxgui``
  2. link to ``xpdAcq`` on github when we mention we can install and run simulation at home

**Comment by sbillinge** [comment]
all done.  Closing.
