### ISSUE TITLE
scanPlan type that is a bluesky pass-through

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#176]
We currently have ``ct``, ``tseries`` and ``Tramp``.

I propose to add ``bluesky`` as a scanPlan type.  This takes as scan parameters in the dictionary a set of messages and documents that will be passed through directly to  bluesky ``Plan``, so it is like the user defining any bluesky ``Plan`` directly, but *decorated* with  all the sample metadata that is also passed to the plan that is then passed to the run engine.

I am not sure if this could work, but I htink it might be simple, and v. powerful.

S

**Comment by CJ-Wright** [comment]
@chiahaoliu I think this is implemented right? If one of us should close

**Comment by chiahaoliu** [comment]
Yes, our run engine now can take arbitrary bluesky plan.
