### ISSUE TITLE
load/get pec1 before ipython session created

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#18]
either solve get_ipython() or instantiate pe1c during startup

**Comment by tacaswell** [comment]
This is a tad cryptic.

**Comment by sbillinge** [comment]
@chiahaoliu , please can you elaborate what this issue is?  Does it relate to loading hte simulator?  If so, please close this issue and transfer it to xpdSim.

**Comment by chiahaoliu** [comment]
@tacaswell  in our packages, we need to use python objects that represent experimental apparatus, such as area detector or temperature controller. Currently I am using `get_ipyhton` to get object from current ipython name space, so I can't `from...import` my modules until ipython session is created. Our goal was to pre-load everything during creating ipython session. (we have put a `999-loadxpd.py` in startup directory) 

Would you recommend adding `from 80-areadetector import pe1c` to our `999-loadxpd` ?or do I have to copy codes in `80-areadetector.py` and instantiate (probably duplicate) a pe1c in `999-loadxpd.py`?

**Comment by tacaswell** [comment]
When they are executed your code in 999-* is run _in_ the current ipython namespace so you already _have_ `pe1c` as a valid reference.

**Comment by chiahaoliu** [comment]
So can I use `get_ipython().user_ns['obj_name']` in `999-loadxpd.py` ? I got an error when I tried.

Details of this import is as following:
In `999-loadxpd.py` there was a line: `from xpdacq.xpdacq import *`
In `xpdacq.xpdacq` there are lines:
``` 
ip = get_ipython()
ip.user_ns['pe1c']
```     

And error came from `from xpdacq.xpdacq import *` when I tried last time.

**Comment by tacaswell** [comment]
What error do you get?

In any event, it is probably better to do something like


```python
from xpdacq.xpddacq import (the, functions, and, classes, you, need, set_ad)
set_ad(pe1c)
```

Instead of having `xpdacq` try to reach out and _find_ the detectors it needs, have the startup file _tell it_ the detectors it needs.

**Comment by sbillinge** [comment]
yes, that makes a lot of sense.

On Mon, Feb 8, 2016 at 5:44 PM, Thomas A Caswell <notifications@github.com>
wrote:

> What error do you get?
>
> In any event, it is probably better to do something like
>
> from xpdacq.xpddacq import (the, functions, and, classes, you, need, set_ad)
> set_ad(pe1c)
>
> Instead of having xpdacq try to reach out and *find* the detectors it
> needs, have the startup file *tell it* the detectors it needs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/18#issuecomment-181604663>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
@tacaswell  For learning purpose, I still want to figure out where does my error come from. Here is my error message:
```
     15 def _get_obj(name):
---> 16     ip = get_ipython() # build-in function
     17     return ip.user_ns[name]
     18 

NameError: name 'get_ipython' is not defined
```
I looked at stackoverflow, and it seems that is still an unsolved problem as long as we call get_ipython() during starting up ipython session with profile. ( it doesn't work even with direct importing modules behind get_ipython)

Any idea?

**Comment by tacaswell** [comment]
Not sure of details of ipython internals, but I suspect that you are trying to get a reference to the object you are in the middle of creating.

**Comment by chiahaoliu** [comment]
Yup, and this object is the ipython session initiated by start_up files, loaded with detectors, bluesky e.t.c....

Does it imply `get_ipython` function is not the right solution we are looking for ?

**Comment by tacaswell** [comment]
Yes

**Comment by chiahaoliu** [comment]
👍

**Comment by danielballan** [comment]
I don't want to muddy the water here -- scraping the IPython namespace should be a last resort and it is probably not the way to go here. But if the day comes when you find yourself needing to do this, notice that ophyd has some (undocumented!) ways of grabbing all devices / motors / etc. See here in the source: https://github.com/NSLS-II/ophyd/blob/master/ophyd/commands.py#L45

**Comment by chiahaoliu** [comment]
This should be fixed using `glbl.py` structure but will test it after testing at XPD computer.

**Comment by chiahaoliu** [comment]
Tested. Close.
