### ISSUE TITLE
getxgui -> xPDFsuite

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#185]
It is important to get our branding right.

1. Change how xPDFsuite is run so it is run by typing ``xPDFsuite``, and ``xpdfsuite`` but not ``getxgui``.
1. Modify the quickstart (and other) documentation to reflect this change.

**Comment by chiahaoliu** [comment]
``getxgui`` was given by Xiaohao/Pavol and it is actully used in current release of ``xPDFsuite``  Instead of modifying the name of this python program, I think will simply make an alias at XPD so that typing ``xPDFsute`` is equivalent to ``getxgui``

**Comment by sbillinge** [comment]
yes, that is all that is needed, but make xPDFsuite AND xpdfsuite aliases.
Then change the documentation so it says "xPDFsuite or xpdsuite"

S

On Tue, May 17, 2016 at 11:05 AM, Timothy Liu <notifications@github.com>
wrote:

> getxgui was given by Xiaohao/Pavol and it is actully used in current
> release of xPDFsuite Instead of modifying the name of this python
> program, I think will simply make an alias at XPD so that typing xPDFsute
> is equivalent to getxgui
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/185#issuecomment-219747374>
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
Remotely added alias at XPD and verified it is wokring

**Comment by chiahaoliu** [comment]
already tested at XPD, close here.
