### ISSUE TITLE
make suspender interactive

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#195]
Now bluesky offers interactive way to install / uninstall suspender in the run time, maybe we can make suspender class we instantiated during startup process accessible to user so that more advanced user can uninstall / install suspender during experiment.

**Comment by sbillinge** [comment]
yes, let's put that in v0.4 milestone.

@Tim, could you also update the target dates for our existing milestones.

We will also need a v0.5 milestone which has the analysis code. (v0.4, if
we need it, will have bug fixes from v0.3)

Thanks,

S

On Thu, May 26, 2016 at 11:48 AM, Timothy Liu <notifications@github.com>
wrote:

> Now bluesky offers interactive way to install / uninstall suspender in the
> run time, maybe we can make suspender class we instantiated during startup
> process accessible to user so that more advanced user can uninstall /
> install suspender during experiment.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/195>
>



-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by sbillinge** [comment]
Advanced user can read the bluesky documentation.  Close for now until real users start yelling for it.
