### ISSUE TITLE
start_beamtime feature 

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#2]
new_beamtime script copies standard mask and config files from standard place (xpdConfig) into working directory (where they are needed.  I guess both should go to xpdUser/config_base.

**Comment by chiahaoliu** [comment]
UC1.
1) BLS exectutes start_beamtime()
2) ``start_beamtime()`` looks for mask files by extension in xpdConfig directory and installs them in ``config_base``
3) ``start_beamtime()`` looks for mask files by extension in ``import`` directory and moves them to ``config_base``

UC2.
1) user installs mask files from import directory after start_beamtime() has been run.  

UC2 implies a separate function  called ``import_mask()`` that can be run from the prompt.  Alternatively, better would be to have an ``import()`` function that imports everything in the import directory.

In this case, delete files from import after they are successfully moved, send message to user that this was done and say "run export_ScriptsEtc() to re-export any installed files."

Then make sure that everything that import imports is exported by export.
