### ISSUE TITLE
auto-masking on image collected

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#200]
This thread is to discuss the workflow about auto-masking

**Comment by chiahaoliu** [comment]
* As discussed with @CJ-Wright this morning, we basically think auto-masking should take place at the integration step. Program hands ``pyFAI`` geometry object to auto-masking function and it generates a ``<tiff_name>.npy`` or ``<tiff_name>.msk`` file that was applied to target tiff. Of course, ``chi`` file will be saved in the same directory too.

* Based on discussion with Soham and Max, we need a consistent way of linking calibration image and mask for this calibration image to subsequent headers. Ideally, we should bundle them together while performing calibration and leave a pointer to this bundle.

* Following is also the comment from @sbillinge on gitlab:
  *I think the workflow is moving in the direction of (a) doing the automask on the calibrant and then using that mask (b) allowing people to do an automask on their own data on demand*

**Comment by CJ-Wright** [comment]
For your second point, can we use:
 1. find the calibration header using the `calibration_uid`
 1. find the location of the calibration images using the `get_events` function
 1. load the masks, knowing that the masks will be named similarly to the images
 1. use the calibration masks to create subsequent masks.

I think a lot of these issues can be addressed when the analysis database is ready.

**Comment by sbillinge** [comment]
Let's discuss and finalize this tomorrow. We are going away from file based
so @chiahaoliu bullets 1 and 2 are moot in the longer term.

**Comment by CJ-Wright** [comment]
Closed, moved to repo mentioned above
