### ISSUE TITLE
BLD: add travis and coveralls?

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#203]
Should we add this project to Travis-CI and Coveralls?

**Comment by sbillinge** [comment]
that would be awesome.  Is it much setup?

**Comment by CJ-Wright** [comment]
Travis doesn't usually take much setup, especially for open source projects (although they do handle private repos). It should be especially easy as we can borrow the `.travis.yml` file from bluesky (that is the most major dependency right?) and edit it to match our needs. I'll put in a PR.

**Comment by CJ-Wright** [comment]
See #204

**Comment by CJ-Wright** [comment]
Closed by #204
