### ISSUE TITLE
TST: A bunch of tests are failing

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#206]
It seems a few things are missing?
Here is the [travis build](https://travis-ci.org/CJ-Wright/xpdAcq/jobs/159941248)
Does anyone know what is going on?
@chiahaoliu

**Comment by chiahaoliu** [comment]
that comes from outdated unittest that I haven't cleaned yet. I will put a PR to just clear this ``tests`` directory (new ones are located under ``xpdac/tests``)

**Comment by CJ-Wright** [comment]
I can get it in this PR if you want.

**Comment by CJ-Wright** [comment]
Closed by #205
