### ISSUE TITLE
confirm that file-based workflow is as desired

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#214]
1) users set current path for saving
2) `save_tiff` saves tiff in current path AND saves metadata in a text file
3) `integrate` saves TWO chi files (Eric and Sanjit requested this). One is on a Q-grid, the other on a 2theta grid
4) make sure that UID is at the very end of the auto-generated filename
5) BUG make sure that the bug that Tramp event index (i.e., 001, 002, etc.) is incrementing correctly.  Check this also for tseries
6) Make sure the xpdView looks at the right directory and updates when refresh is pushed.  We should discuss exactly how we want the default behavior to be....xpdView always looking a "current" directory, or being manually changed to "current" directory
7) As (6) but for xPDFsuite

**Comment by chiahaoliu** [comment]
for 5), this index is actually read out from ``metadatastore`` so I would be surprised if there is a problem. 

I will contact them if they have further examples.

**Comment by sbillinge** [comment]
The instrument scientists were reporting a problem, so it may be a bug with the bluesky Plan, but the issue can't be closed until it is tested.  If necessary, move this to a separate issue.

Please note, I just added a new thing in the list

**Comment by chiahaoliu** [comment]
for 6) and 7), would it make sense to let user choose directory? Since we now categorize image and chi files based on sample names.

**Comment by sbillinge** [comment]
See #294  for tasks left to do from this issue. Everything else completed so closing.
