### ISSUE TITLE
Sanjit request to access event level metadata

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#215]
We need to define this more carefully, but Sanjit wants event metadata that is defined in user-defined scans to be available in the metadata file that is saved with the data

**Comment by chiahaoliu** [comment]
This should be possible. Currently we are saving ``run_start`` metadata into a yaml file. We can always insert event ``data``field to this yaml file too since current saving/integrating function is actually operating on event level.

but maybe they prefer ``csv`` over ``yaml``?

**Comment by sbillinge** [comment]
yes, let's switch to csv

**Comment by tacaswell** [comment]
What is 'event metadata'?  How would a switch to csv (which requires tabular data) work with the runstart (which is mostly (key, value) data)?

**Comment by CJ-Wright** [comment]
I think 'event metadata' is event level data which is not detector images, eg. motor positions, temperature, etc. Is that correct? @sghose

**Comment by danielballan** [comment]
I have not seen any scans done at XPD that would require a muxer. Sanjit came to my databroker tutorial today and learned how to get a table of measurements (including "metadata" if motor positions/temperature are metadata) and export to CSV.

**Comment by CJ-Wright** [comment]
Hmm, ok. That works too! I thought that some of the RGA data could have been async.

**Comment by sbillinge** [comment]
I think this conversation is derailing....the file we are talking about is a human readable output for XPD users that will go away when we move away from our file-based workflow.   The users are more familiar with csv, will be more freaked out by yaml, even though it is a text file too.....

S

**Comment by sghose** [comment]
Sorry for lengthy email but vert details and exact to avoid confusion.

Seems now we know what Sanjit/Users at XPD want. I have no idea about muxer functionality. But, as Dan says, I can now search and write stuffs into a csv file. Let me put into simple language what we need at very high level (in xpdAcq). 

All we need the csv file to contain a well formatted (spread sheet style columned and row) data, time (up to sec) , tiff file uid, may be integrated intensity for the whole frame. Here, data means metadata as inserted in the scans or runs. For example, in our star up directory/*user_scans*.py file, we have a few functions written by DAN/Chris/Tim ( MED, better_MED, gas_temperature etc) where we have meta data such as Eurotherm, Temperature, Gas, RGA ( channel-1 to 3). We need all these as a human readable text file after each scan deployed in xpdAcq. 

We do save_tiff to save tiff. All we need to do save_anal to convert & save 1D integrated etc  and we could do save_md to save csv file. We could be little smarter in putting fields ' motor position', 'Temperature', 'gas', as many stuff we need but time, tiff hid etc should be there by default.

Currently I am doing all these opening another Bluesky session and running scripts. The same scripts could be implemented into xpdAcq. This will make our(my life) each for some users as we  would like to use xpdAcq to run Bluesky functions.

**Comment by chiahaoliu** [comment]
Thanks for your reply @sghose . So maybe you can send me the code you are currently using so that we can have a better understanding of what user needs and how we can implement it? Thanks.

**Comment by chiahaoliu** [comment]
This request has been fulfilled by working side-by-side with @sghose this afternoon.
Now beamline scientist has convenient function written to save event data into csv file.

Once @sghose double confirm, I can close this issue.

**Comment by danielballan** [comment]
What is Event-level metadata?

**Comment by chiahaoliu** [comment]
Based on conversation with beamline scientist, event-level metadata could be motor positions, readout from detectors or both, in this context.

After discussing with beamline scientist, current implementation is:

1. beamline scientist uses plans with LiveTable, either from bluesky or from xpdAcq 

2. Instruct beamline scientist to observe field names appeared in the LiveTable and copy&paste/memorize them.

3. Beamline scientist use helper function that takes a header, a list of field names and file name of csv data. Function saves file with desired file name and fields in interest.

Underneath the helper function is simply ``get_table`` and ``to_csv`` method from pandas

**Comment by danielballan** [comment]
Cool. Makes sense.

**Comment by sghose** [comment]
Dan your Bluesky Tutorial Session-1 that I took helped a lot. I could not made to the Tutorial-2 yesterday while working with Tim.
I would like to go for the second one for sure next time.
Tim made the functional very simple and legible. I am sure I can extend this to other Blusky plans. My next exercise will be to workm along git and then push any stable plans into XPD startup for user to use.

Sanjit

**Comment by chiahaoliu** [comment]
close based on @sghose 's reply
