### ISSUE TITLE
agenda for how the rollout will progress on Thursday

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#222]
something like a ppt slide or two that you will present at the meeting, and what you expect the instrument scientists to do.  Ideally they should be given documentation and then just follow it to run a fake experiment and visualize the output.  Can we simulate something like that without data?

**Comment by chiahaoliu** [comment]
I have both simulation and acquisition working under simulation, it just needs small tweaks to make code look nice. But I was able to run entire workflow, from ``_start_beamtime`` to ``integrate_and_save_last`` and then refinement, with a pre-populated data (``Ni``)

I also have uid  for image we collect last time. ``xpdAn`` functionality can demonstrated on that.

For that slides I am thinking to just include new features introduced in this release, like ``integration`` and ``import_sample``

**Comment by sbillinge** [comment]
Great news.

have them go through a step-by-step process so that THEY do what you did
with the workflow by following documentation....you only jumping in when
they get stuck (and making a note to update the documentation there).  It
should look a bit like a chapter of PDFttp....
