### ISSUE TITLE
automask workflow described in documentation

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#223]
on cheatsheet, and in quickstart and main part of documentation

**Comment by CJ-Wright** [comment]
Is there one documentation going out for the combined Acq and An repos?

**Comment by sbillinge** [comment]
one user documentation.  

Developer docs are all in the codes and so are somewhat separated.

**Comment by CJ-Wright** [comment]
Closed, moved to repo mentioned above
