### ISSUE TITLE
MTN/TST: move to pytest

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#225]
Should we move tests to pytest? Many other of our dependencies have made this move and I think it will make writing tests easier.

**Comment by chiahaoliu** [comment]
currently I use ``py.test`` inside ``tests/``, but I guess you meant a more sophisticated, ``python run_test.py``?

**Comment by CJ-Wright** [comment]
I meant more using their test fixtures rather than unit tests objects. For example building a beamtime test fixture rather than building it in a setup method.

**Comment by sbillinge** [comment]
Let's do it.

**Comment by st3107** [comment]
Done.
