### ISSUE TITLE
simplifying load sample sequence

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#226]
Since we are in an environment that knows the current saf number, and the sample file is saved with that saf_number, can't we do the following.  Instead of 

 `import_sample(<saf_number>,` bt)`

it could be

`import_sample()`

where the defaults in `import_sample` are `saf_number = bt.md.saf_number`.

If this is difficult because bt is not known in the function namespace, don't lose sleep over it, but in general it is annoying for users to type the same stuff (e.g., saf number) over and over again.

**Comment by chiahaoliu** [comment]
that should be doable, it will be included in PR #209

**Comment by chiahaoliu** [comment]
PR #209 is pulled in. closed
