### ISSUE TITLE
autonaming of scans?

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#23]
Scan naming is pretty critical.  I think we should think about autonaming them.

count:
ct<#>   where # is count time.   Then add vw, lt and/or ns if they are set to true.  e.g., 'ct2.5.vwlt'
Tramp:
T<startT>_<stopT>_<Tstep>.vwltns  e.g. 'T280.5_280.9_0.1.vwlt'

sthg like that

**Comment by tacaswell** [comment]
between `str.format` and `jinja2` this should not be technically hard (agreeing on the format + what to name the input keys maybe harder).

**Comment by sbillinge** [comment]
I still think this would be better behavior.  Let's do it.

For ``'ct'`` => ``'ct#.#u'`` where #.# is a number and u is a unit, e.g., ``ct1s``, ``ct1.5s``, ``ct1.5m``
For ``tseries`` => ``tsn#1_e#2_d#3`` where numbers 1-3 are number of steps, exposure, delay
For ``Tramp`` => ``Tr#1_#2_#3_#4`` where 1-4 are startT, endT, Tstep, exposure

**Comment by chiahaoliu** [comment]
I finished implementing this functionality but I would like to propose a slightly different format, which doesn't contain units in auto-naming schema. Here is the docstring from my parser:
```
expected format for each type is following:
1) 'ct_10' means Count scan with 10s exposure time in total
2) 'Tramp_10_300_200_5' means temperature ramp from 300k to 200k with 5k step and 10s exposure time each
3) 'tseries_10_60_5' means time series scan of 10s exposure time each scan and run for 5 scans with 60s delay between them.
```
My motivation was to keep SI unit across package to avoid confusion and also keep our code cleaner.
Does it still sound good ?

**Comment by sbillinge** [comment]
yes, I think you are right.  I added units to make it more readable and
less ambiguous, but if we force users to use SI it is not ambiguous and not
so unintuitive either for most people.  Giving meaning by position is also
fine, we just have to make the documentation clear.  Yes, go with this.

Maybe we should have it generate a print statement though that lays out
explicitly what has been requested.

S

On Wed, Apr 27, 2016 at 1:32 PM, Timothy Liu <notifications@github.com>
wrote:

> I finished implementing this functionality but I would like to propose a
> slightly different format, which doesn't contain units in auto-naming
> schema. Here is the docstring from my parser:
>
> expected format for each type is following:
> 1) 'ct_10' means Count scan with 10s exposure time in total
> 2) 'Tramp_10_300_200_5' means temperature ramp from 300k to 200k with 5k step and 10s exposure time each
> 3) 'tseries_10_60_5' means time series scan of 10s exposure time each scan and run for 5 scans with 60s delay between them.
>
> My motivation was to keep SI unit across package to avoid confusion and
> also keep our code cleaner.
> Does it still sound good ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/23#issuecomment-215162368>
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/
