### ISSUE TITLE
bluesky plan passthrough

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#24]
we have 'ct', 'tseries' and 'Tramp'.  If we just add a function that takes as arguments (metadata object, blueskyplan, scanparmsDict) then we can run any bluesky plan that users create with all the metadata that we have created saved too.  We will have to wrap a pointer to the plan in the scan_parms dictionary inside an xpdacq ScanPlan and then unpack it in prun, for example, but it should be easy.

Putting this for 2/14 milestone, but I am ok with it slipping to 2/28 if necessary.

**Comment by sbillinge** [comment]
noone has requested this yet, so pass it to v0.4

**Comment by CJ-Wright** [comment]
Has this been closed by #191

**Comment by danielballan** [comment]
I would say this can be closed. As of #202, xpdacq's `prun(some_plan)` works for any plan (any iterable object that yields `bluesky.Msg` objects), whether or not that plan is aware of xpdacq.

**Comment by CJ-Wright** [comment]
Great! closed by #202
