### ISSUE TITLE
Issues arising from test of Demo

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#247]
1. change ipython prompt to show `(collection)` and `(analysis)`
1. add words in docs about whether to be typing in collection or analysis during the demo
1. preload sample[0]. For now by loading a template file during startup (brittle)
1. clean up old directories here there and everywhere
1. Leave Ni in the beam for the demo
1. default setup ScanPlan ([0]) should be 5s
1. change SrXgui config to point at new tiff_base
1. words in documents suggesting not to build the bluesky plan during the tutorial walkthrough
1. samples[5] -> samples[2] in docs
1. "depending on your sample, in docs

**Comment by chiahaoliu** [comment]
fix in #248

**Comment by sbillinge** [comment]
Please use past tense, fixed, if that is what you mean. Fix could imply it
needs to be fixed in the future.

S

**Comment by sbillinge** [comment]
All done.
