### ISSUE TITLE
Handle suspenders in macros

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#251]
The current macro logic uses multiple invocations of the run engine. This can cause potential problems when the nth run engine suspends, hands control back to the macro which then starts the n+1th run engine, completely bypassing the suspension. We might deal with this by having suspender conscious logic at the prun level.

Two key suspenders to handle:
- [ ] Beam Dump
- [ ] Control-C

In discussion with @sbillinge

**Comment by chiahaoliu** [comment]
I think that was the situation for ``v0.4`` before. A big change of ``v0.4`` is instead of calling a ``run_engine``,  ``prun`` itself is a ``run_engine`` so ``suspender`` and other related functionalities would work seamlessly.

maybe we want to discuss what behavior do we want for ``beam dump`` and ``control-C``?

**Comment by CJ-Wright** [comment]
I think that the main issue is that if you have a script like this:
```python
run_calibration()
run_mask()
run_sample()
etc.
```
That if any one errors the script, which is not a bluesky plan will keep going.

**Comment by sbillinge** [comment]
This is a workaround that we seek to allow users to write macros with
multiple invocations of xrun (prun is history folks) but have them less
susceptible to the suspender issue.

In the long run we will explore writing macros as BS plans, but I am not
ready to go there yet for a number of easons. So the question is whether
there is a quick and dirty workaround such as querying the state of the
xrun run engine before executing the next action in the macro, and looping
with pauses until it returns "stop", sthg like that.

As Chris pointed out, this will work for beam dump case but will be clunky
for CTL-C

S

**Comment by CJ-Wright** [comment]
Is this still an issue? @chiahaoliu

**Comment by chiahaoliu** [comment]
This issue has been taken care by making ``xrun`` as a subclass of ``RE`` and link suspender directly. Close.
