### ISSUE TITLE
`integrate()` should also save a header metadata yml file

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#256]
This is done in `save_tiff()` logic, but it should also be done as part of the `integrate()` logic.  It may already be, but let's check and make sure.

**Comment by chiahaoliu** [comment]
This was fixed in xpdAn PR 32 (but not merged in yet)

**Comment by CJ-Wright** [comment]
I'd be more than happy to merge xpdAcq/xpdAn#32 as soon as the mask flipping issues are resolved.

**Comment by CJ-Wright** [comment]
closed by xpdAcq/xpdAn#32
