### ISSUE TITLE
Adjust how users execute user-scripts now we are in `/pe1_data/` space

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#257]
Either adjust the documentation to give the full path, but this is a very brittle solution.

A better one _may_ be to redefine `~/` to point to `pe1_data/...`

**Comment by CJ-Wright** [comment]
Related: we might also try to put the processed data in pe2_data just so we don't run the risk of people deleting/editing the wrong folder

**Comment by chiahaoliu** [comment]
setting ``~/`` to ``pe1_data/`` might require help/authorization from IT, but I can brought it up to XPD beamline team.

**Comment by sbillinge** [comment]
We should look into using pe2_data for xpdUser as a further way of hiding
the srchives

**Comment by sbillinge** [comment]
make a simlink to xpdUser so users can just type cd xpdUser and it goes to the right place.

**Comment by sbillinge** [comment]
@chiahaoliu needs to do some testing on this issue, so move it to v0.5patch milestone

**Comment by CJ-Wright** [comment]
We need softlinks

**Comment by CJ-Wright** [comment]
I think this is done.
