### ISSUE TITLE
refactor get_light_images and collect_temperature_scan to look more like collect_time_series

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#26]
I like the way that Tom did it better, so when we have tested time series and made it work in #25 it would be good to refactor the count and Tramp functions to look more like that.

**Comment by chiahaoliu** [comment]
`get_light_image` and `collect_temperature_scan` are following the same structure as `collect_time_series`. Once we refactor `glbl.py` so that python objects like `pe1c` are handed correctly to `xpdacq.py` and we change the syntax in these functions, we can close this issue.

**Comment by chiahaoliu** [comment]
They are in the same form after refactoring from PR #156. Can we close it now?
