### ISSUE TITLE
save timestamp up to seconds in tiff file name

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#262]
as @sghose request

**Comment by sbillinge** [comment]
I recommend to test just making the default behavior to save to the seconds level.  Will this affect other users negatively?

This is the least work as it just means updating `_timestampstr()`.  It is the least disruptive to the API and just adds two digits (and a colon?) to the filename.

**Comment by chiahaoliu** [comment]
yes, sounds like a good plan
