### ISSUE TITLE
need a function that deletes ex, sa and sc yaml files

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#27]
delete_acq_object(object_name,object_type)

Simply deletes the yaml file from the yml directory.

**Comment by chiahaoliu** [comment]
I would imagine it to be in a `classmethod` in `bt`. Is it right?

**Comment by sbillinge** [comment]
yes, I think so.  We have bt.list() bt.get(), so I imagine we could have bt.del().

Probably have it ask for confirmation
"I am about to delete '+ObjetType+' object with name '+name+'. Do you want to continue y/[n]:'

For safety we could also just move it to another directory outside of yml rather than delete it.  All the user wants is for it not to appear in the list any more.

S
