### ISSUE TITLE
take user input when running xrun without wavelength inside bt

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#275]
gently warn user and ask if user wants to proceed

**Comment by sbillinge** [comment]
We need to revisit this.  I am not sure what problem it is solving.

**Comment by sbillinge** [comment]
WARNING: no wavelength set.  Obtain the correct wavelength and run bt.wavelength = <value> to make a auto-reduction work properly.

add a wait 5s
bt.warningWait = 5s

bt.warningWait = 0
