### ISSUE TITLE
revisit behavior of import_sample_info

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#283]
mongo doesn't allow `.` in the key field so we can not  have metadata like:

`{'sample_composition':{'0.8mm_glass_capillary': 1}}`

need to rethink the behavior carefully.

**Comment by CJ-Wright** [comment]
Please see the remarks in #339

**Comment by sbillinge** [comment]
@chiahaoliu I don't think you want me to review this issue, right?  It is part of a PR that is being reviewed.  Or is there something special in this issue itself that is not in the PR discussion?

**Comment by CJ-Wright** [comment]
I put this in the review board, I wanted to make certain that the potential for revert and Tom's comments were seen.

**Comment by sbillinge** [comment]
OK.  I think we maybe should revisit the schema briefly before anything else.  Having a sample name as a key doesn't seem quite right, though presumably there is a reason....can we schedule a face-to-face discussion on this?  It could only be 5 mins....

**Comment by chiahaoliu** [comment]
Yes, I think that is a good idea. Please let me know anytime that is good

**Comment by chiahaoliu** [comment]
I will be in starting from tomorrow
