### ISSUE TITLE
xrun issue happens quite often after inserting a new sample name and import. But not always.

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#284]
In [2]: import_sample_info()
INFO: using SAF_number = 300658
*** End of import Sample object ***
Out[2]: <xpdacq.utils.ExceltoYaml at 0x7fc8b69633c8>

In [3]: bt.list()

ScanPlans:
0: 'ct_5'
1: 'ct_30'
2: 'ct_60'
3: 'tseries_1_0.1_3000'

Samples:
0: bkgd_1mmOD
1: Ni_calibrant
2: TiO2_sintered_7_800C_pdf_40V

In [4]: xrun(3,1)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-543c6cbfcde1> in <module>()
----> 1 xrun(3,1)

/home/xf28id1/xpdAcq/xpdacq/xpdacq.py in __call__(self, sample, plan, subs, verify_write, dark_strategy, raise_if_interrupted, **metadata_kw)
    365         if isinstance(sample, int):
    366             try:
--> 367                 sample = self.beamtime.samples[sample]
    368             except IndexError:
    369                 print("WARNING: hmm, there is no sample with index `{}`"

/home/xf28id1/xpdAcq/xpdacq/xpdacq.py in beamtime(self)
    323     def beamtime(self):
    324         if self._beamtime is None:
--> 325             raise RuntimeError("This CustomizedRunEngine was not "
    326                                "assigned a beamtime object, so integer-based lookup is not "
    327                                "available.")

RuntimeError: This CustomizedRunEngine was not assigned a beamtime object, so integer-based lookup is not available.

**Comment by sbillinge** [comment]
Change RuntimeError message to 
"your beamtime environment is not correctly set up.  At the prompt, type: 
xrun.beamtime = bt
and retry."
