### ISSUE TITLE
Save_last_tiff() for 500 files takes 10 minutes: New issue

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#286]

**Comment by CJ-Wright** [comment]
Is the code as optimized as it could be running on a single processor?

**Comment by CJ-Wright** [comment]
Also can you post a profile of the code? (I am trying assess if this is an issue where we can fix it on the kernel side or we need to multiprocess)

**Comment by chiahaoliu** [comment]
for the record, this issue was opened by @sghose by accidentally used my account left at XPD.

tag him here so that he can receive notification about this thread.

**Comment by chiahaoliu** [comment]
I think this issue is resolved at current version. Close for now. @sghose please reopen it if needed.
