### ISSUE TITLE
remove plotting logic from save_tiff in analysis.py

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#29]
save_tiff() should save a tiff file, not plot it.

Then we need another function called plot_tiff() where we put that plotting logic.

**Comment by chiahaoliu** [comment]
in pull request `f375ada70e52cf3528ec2156df317365334100bd`

**Comment by sbillinge** [comment]
I don't see that pull request....where is it?

**Comment by chiahaoliu** [comment]
next to `issue` button at repository page

![image](https://cloud.githubusercontent.com/assets/15218640/12908021/61c967e2-cec0-11e5-87a5-463eb60f7c5e.png)

**Comment by sbillinge** [comment]
We probably need a different naming scheme.  That pull request refers to a
different issue, but I guess all your commits get merged into the same pull
request?

On Monday, February 8, 2016, Timothy Liu <notifications@github.com> wrote:

> next to issue button at repository page
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/15218640/12908021/61c967e2-cec0-11e5-87a5-463eb60f7c5e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/29#issuecomment-181711787>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
I pushed all my changes to `develop` branch under my fork and I specify changes in different `commit` messages. 

I think I'd better separate different issues into different pull requests

**Comment by tacaswell** [comment]
Lots of PRs actually keep the development work flow much neater.  By reducing the scope of the changes it makes it easier to review and easier to keep track of what you are doing.

**Comment by chiahaoliu** [comment]
Got it! But can I still make multiple PRs if I only push to one branch?

**Comment by tacaswell** [comment]
no, PRs are bound to a single branch.  Luckily branches are free in git!
