### ISSUE TITLE
BUG: fix beamdump suspender

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#291]
Beamdump suspender seems to reset it's threshold value on scan start, causing issues when starting scans during beam dump.
@tacaswell

**Comment by CJ-Wright** [comment]
See #72 for rich diagnostics from @sbanerjee23

**Comment by sbanerjee23** [comment]
Oh heck yes, this one made my day!

**Comment by tacaswell** [comment]
This is a feature that is someplace in xpdacq not a feature of suspenders.

**Comment by sbillinge** [comment]
- create suspender at start_beamtime
- heuristic is that threshold is 50% of current current or 50mA (check), whichever is higher.  If it defaults to the 50mA option, issue a warning.
- WARNING: suspender set when beam current was below 50 mA.  For best operation, run set_suspender(xrun) when beam current is at its full value.
