### ISSUE TITLE
revisit _end_beamtime process when user data is huge

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#304]
possible solution:

during `_end_beamtime`, rename `xpdUser/` as `xpdUser_archive/` first so that `_start_beamtime` can be run while program is archiving local directories.

need to test how fast is the renaming step first then we can make the archive step working in the background process.

**Comment by chiahaoliu** [comment]
After comparing between different threading modules, the best solution to our situation might be using ipython ``BackgroundJobManager`` class. Please see reference [here](http://ipython.readthedocs.io/en/stable/api/generated/IPython.lib.backgroundjobs.html)

In this way, we can completely free current ipython session, without predicting what user would do during this long archiving process and output of  ``_end_beamtime`` will be returned as well.

complete command history would be:
```
from IPython.lib.backgroundjobs import BackgroundJobManager

job = BackgroundJobManager()
job.new(_end_beamtime)
````

Instantiation could be done from our side, but is it fair to ask beamline staff typing ``job.new(_end_beamtime)`` ?

Any thought? @sbillinge @CJ-Wright

**Comment by CJ-Wright** [comment]
For the record we should use some form of multiprocessing not threading, as we might not release the GIL in the background code causing it to eat up all the resources. If the `BackgroundJobManager` does this then that is fine by me.

**Comment by chiahaoliu** [comment]
Unfortunately, ``BackgroundJobManager`` is indeed a subclass of ``Threading`` class (based on its documentation). I don't have much experience with multiprocessing but based on what I've found, it seems we need to know what subsequent operation is so that we can utilize ``join`` method from multiprocess class. Is that correct?

Basically, we want our ipython session to be free during the archiving process, regardless what operations are followed by and we would need the return of ``_end_beamtime`` once it is done. 
Can you shed some light on this aspect?

**Comment by CJ-Wright** [comment]
It is standard to join at the end of a mutiprocessing run. [Python Futures](https://docs.python.org/3/library/concurrent.futures.html) might be of interest, although I don't have experience with that.

**Comment by sbillinge** [comment]
Let's go with @chiahaoliu suggestion for now, until it results in problems.  However, I would ask that there is a check that the archived data-tree has the same size as the original tree, before it is deleted locally.

**Comment by chiahaoliu** [comment]
Repost in #399. Close for now.
