### ISSUE TITLE
by default, exclude setupscans()  in searches

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#31]
these contain the metadata key ex_ispr set to False (check the exact name).

all searches should therefore have (Setups='no') as an optional argument.
other allowed values should be 'yes' and 'only' (there may be a better way to do a 3-way truth logic, in which case use it, but this can work.

**Comment by CJ-Wright** [comment]
Move to An

**Comment by sbillinge** [comment]
moved to xpdAn
