### ISSUE TITLE
ENH: formalize required fields into schema

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#314]
We should formalize what fields we need for each run start (PI name, sample name, saf#) in a json schema so that we can validate the results, also this will help with building test suites, as we can build fake MDS documents with the correct fields.

**Comment by danielballan** [comment]
You probably already got here, but allow me to suggest `jsonschema.validate` and `xrun.md_validator`. :- )

**Comment by CJ-Wright** [comment]
Can I please get this for the upcoming release? It is super important to know what we have and what we don't have for search generation.

**Comment by sbillinge** [comment]
@CJ-Wright are you asking for the schema that currently exists from `xpdAcq`?  We should definitely record this ( @chiahaoliu ).   But it is a bit of a cart and horse issue.  Depending on what we _want_ to search for (captured in the UC's and queries we have been generating) we will figure out what we need to capture in the metadata.

But to get it started, let's formalize a record of the schema.  @danielballan @tacaswell what is the best way to publish a schema?

**Comment by danielballan** [comment]
See our event-model repo for an example.

**Comment by CJ-Wright** [comment]
I think they might need to be developed simultaneously.

I guess I am asking for three things:
1. A schema version number applied to all the xpdAcq produced start headers for the xpdAcq schema.
1. A concrete schema for all the currently captured/mandated metadata. (Note that this doesn't change anything about the existing system, it just tracks what we are already saving as metadata)
1. A discussion about if we are missing any important pieces of metadata, which should be added to a new version of the schema. (this will most likely require some discussion of searches and what searches are difficult/impossible based upon our current schema, for example should we splay some of our existing data in dictionaries into the main header to make for easier db.search()ing)

The hope is that with the version numbers in the schema we can produce code which understands that the mandated data in the headers can change (eg a search knows that the schema for v0 has a bunch of data in a dict which we splayed out in v1 so it changes the query to fit the header)

To follow up on @danielballan's comment [here](https://github.com/NSLS-II/event-model/blob/master/event_model/schemas/run_start.json) is a link to the `run_start` schema. xpdAcq requires a lot more metadata than this so it may be good to codify that.

**Comment by danielballan** [comment]
Also see this excellent tutorial (not by me!) https://spacetelescope.github.io/understanding-json-schema/

**Comment by CJ-Wright** [comment]
This has its own repo now.
