### ISSUE TITLE
make sure all files in Acq contain the columbia/Billinge-group copyright statement

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#316]
Just some cleaning, but important for sociological reasons....

btw, I don't think all the documentation files need this....just the code.

**Comment by CJ-Wright** [comment]
We might write a linter for this so that github will auto check the licence on every PR.

**Comment by sbillinge** [comment]
haha, I was hoping that I would receive a response something like
that...... ;)

**Comment by CJ-Wright** [comment]
Yea well you know me a total sucker for automation (hence my love of software).
[Xonsh](https://github.com/xonsh/prlint) seems to do this well, I might try to steal their setup.
