### ISSUE TITLE
ENH: insert facility into header MD

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#318]

**Comment by CJ-Wright** [comment]
We also need to make a point to enforce the SAF number, since we are going to use that as a one-to-one mapping for each beamtime.

**Comment by chiahaoliu** [comment]
@CJ-Wright facility information ``owner=xf28id1, group=XPD``  has been linked to ``xrun`` when we instantiate it. Do we need to inject more specific details?

**Comment by CJ-Wright** [comment]
`facility=nsls-II`, `beamline=28id2`?
