### ISSUE TITLE
BUG: register dark at end of dark run

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#325]
It seems that we register the dark as existing when we call the dark image taking plan, however if aborted this can lead to darks not existing when we should have taken another set of darks. We either need to a) only register a dark if the dark plan ran to completion or b) check that the dark run has images inside the events before registering it.

**Comment by chiahaoliu** [comment]
yes, that could be an edgy case wasn't considered when designed. I will look into it.

**Comment by chiahaoliu** [comment]
as a quick note:

we need to think what behavior is desired if the dark header doesn't actually contain an image.

**Comment by CJ-Wright** [comment]
I agree. Maybe we can use the latest dark image? Ideally we don't run into this problem by double checking that the dark images exist. Anton found this bug.

**Comment by danielballan** [comment]
Drive-by suggestion: (a) smells like the right approach to me.

**Comment by chiahaoliu** [comment]
I was thinking about possible logics to this fix, maybe I can have some comments for both of them.

possible logic:
a) don't register dark header unless there is an image in it and issue a print statement saying: "this dark header is not registered, if a fresh dark image is needed, please try again" or something like that. 

b) somehow has ``take_dark`` function recursively called until there is a dark image (implementation detail is not clear) then register the dark header with image.

a) it straightforward but might be slightly inconvenient for users as they have to redo it multiple times. (hopefully two times)
b) reduces the complexities for user but I don't know if this approach is even encouraged under ``bluesky`` framework.

@tacaswell @danielballan ? thanks.

**Comment by CJ-Wright** [comment]
Personally I'd like to avoid a). The taking of dark images should be mostly handled by the code side, not as much by the users (unless they directly request one). For be we might not need a recursive call, just a while loop that checks if a valid dark exists and if not tries to take a dark (we might also want a counter in there so we don't loop indefinitely if something breaks, this could also be handled by a for loop with `if darks_exist: break` logic)

**Comment by CJ-Wright** [comment]
@chiahaoliu status?

**Comment by chiahaoliu** [comment]
PR is almost ready but I got stuck in writing a detector that always fails the scan, which is needed in order to complete the test

**Comment by danielballan** [comment]
@chiahaoliu Is what you were asking about awhile back? Here's a more concrete version of the hasty advice I gave on Hangouts:

```python
class SentinelError(Exception):
    # a custom exception type so we definitely know this was us
    ...

class ErroringDetector:
    # implement all the required attributes and methods to make the RunEngine happy
    def __init__(self, name):
        self.name = name
        self.parent = None
    def read(self):
        return {}
    def read_configuration(self):
        return {}
    def describe(self):
        return {}
    def describe_configuration(self):
        return {}
    # and now a trigger method that will raise an error that will propagate through
    # to the RunEngine and cause it to error out
    def trigger(self):
        raise SentinelError("I broke this on purpose. What are you gonna do?")

**Comment by danielballan** [comment]
...and then in a test you can do something like:

```python
import pytest
from bluesky.plans import count
from bluesky import RunEngine

def test_broken_detector():
    RE = RunEngine({})
    det = ErroringDetector('foo')
    with pytest.raises(SentinelError):
        RE(count([det]))  # triggering the detector should raise an error

**Comment by sbillinge** [comment]
Not sure if it is redundant at this point, but maybe the flow logic could be that we never continue after a dark, but loop back
