### ISSUE TITLE
scan degeneracy problem

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#33]
A scan is a combination of a Sample object and a ScanPlan object.  But it occurs to me that this is not unique because we could run that same combination more than once.  To break this degeneracy we should assign a new uid when the scan is run.  This may be redundant as I think bluesky does this, though it will not be at the same level of the metadata tree so possibly harder to search for?

Need to think about this but it is rather critical.

**Comment by danielballan** [comment]
This is what bluesky offers:

```python
db['unique id']  # equivalent to db(uid='unique id')
db(plan_type='MyPlan', billinge_sample_idenifier='abc')
```

Offhand, I think you only need one unique ID per scan. What other kinds of searches will you want to perform?

**Comment by danielballan** [comment]
P.S. The second line above, `db(plan_type='MyPlan', billinge_sample_idenifier='abc')`, returns a list of headers. Each one is course uniquely identified by its uid.

**Comment by sbillinge** [comment]
Yes, confirmed that we can rely on bluesky uid for this.  Simon closing
