### ISSUE TITLE
make bt a singleton object

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#34]
This should be a singleton, but right now there is nothing stopping a user instantiating a new bt object.

Also nothing stopping them overwriting the existing one.  I would like to avoid that if possible.

@tacaswell I am assigning this to you for comment.

**Comment by danielballan** [comment]
Chiming in here: take a look at SingletonConfigurable http://traitlets.readthedocs.org/en/stable/config.html, or consider that a Python module (or module-level variable) is one way of having a singleton.

**Comment by tacaswell** [comment]
I would also add that in metadatastore, filestore, and databroker we _thought_ we wanted singletons and are now (painfully) discovering that that is not true.

**Comment by sbillinge** [comment]
yes, not 100% committed to the singleton idea, but I want to avoid users overriding the beamtime object that is created for them by the beamline scientist at startup, which has a standard name 'bt'.

I can't think of a use-case where they will need to do that for real....but you never know of course....

This one is not critical for next beamtime, it is actually solving a problem that we haven't had yet, which is usually a bad idea ;)

**Comment by sbillinge** [comment]
I htink we will refactor a bit the object creation, especially the bt object, so we can revisit this later when we do that.  Therefore Closing
