### ISSUE TITLE
ENH: implement the auto_count functionality

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#346]

**Comment by sbillinge** [comment]
I don't see anything to review here.....did this get into review Q/A by mistake?

**Comment by CJ-Wright** [comment]
This is to maximize statistical significance of data while minimizing acq time, with the constraint of not burning the detector and the maximal photon flux.

**Comment by CJ-Wright** [comment]
We also need more info about what the intensity vs. time/photons graph looks like so we can stay in the linear regime.

**Comment by CJ-Wright** [comment]
This problem can be cut into two:
1. How long can we expose for until we burn out. This could be solved by taking a single shot then calculating if it is above the "burnout threshold" if so throw in filters, if not dial up the acquisition time.
1. How many frames do we need before our data looks good. Potentially integrate the data with a normal p-test function, which will examine each binned curve for normalcy, keep going until everything is p>.95 gaussian.

**Comment by CJ-Wright** [comment]
Duplicate See #333
