### ISSUE TITLE
 ENH: data visualization

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#347]
possible directions:
  * reverse-engineer xpdview for integration into xPDFsuite
  * make xPDFsuite py3-compatible

**Comment by sbillinge** [comment]
@chiahaoliu I need a few words about what you want me to do here...again, nothing to review yet, or did you want a priority set or sthg?  Thx.

**Comment by chiahaoliu** [comment]
@sbillinge sorry for confusion

This thread was to initialize a discussion about the direction and priority set of this issue.

Based on our email discussion within us and @CJ-Wright, we might want to take option 2: make xPDFsuite py-3 compatible. However, we might need to prune some functionalities if it is too expensive to make it py-3 compatible.

Preliminary discussion is that:
 1. we need to have full py3 compatible ``Traits`` and ``Chaco`` (which might already be the case)
 2. we need to have py3 version of ``pdfgetx`` (which already exists)
 3. we might want to replace ``srxplanar`` with pure ``pyFAI``. In this case, we are likely to need a new but relative light gui interface to for calibration parameters.
We also need to discuss how to allocate the workloads.

New issue might come out after working on it, welcome to post discussion/issues as it goes.

**Comment by chiahaoliu** [comment]
This will be handled by ``xpdAn`` and ``redsky`` with the streaming pipeline. Close for now.

cc. @CJ-Wright
