### ISSUE TITLE
generate a warning if someone is going to overwite an existing object

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#35]
objects are specified by name and type so if the proposed name and type are already present, issue a warning.

Except for the bt object, I want users to be able to overwrite objects to  update metadata, so don't rule that out, but do give a warning and ask for confirmation before proceeding.

**Comment by danielballan** [comment]
Note: In our experience, users ignore warnings. I suggest you raise an error and force the user to pass an optional argument like `overwrite=True` if they really mean it.

**Comment by sbillinge** [comment]
yes, this is the behavior I want, thanks Dan.  Now, where is that thumbs-up emoticon?

**Comment by tacaswell** [comment]
: + 1 :  with out the spaces

**Comment by sbillinge** [comment]
:+1:

**Comment by sbillinge** [comment]
This should be fixed with the new behavior that objects are never destroyed.  test and close.

Actually it is already tested, so I am closing....
