### ISSUE TITLE
[DOC] full documentation for sample spreadsheet

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#354]
including updating parsing logic, explaining the motivation of filling required fields and some examples, including how to fill in maps for high-dimensional sample information

**Comment by CJ-Wright** [comment]
#376

**Comment by chiahaoliu** [comment]
full sample spreadsheet document was included in PR #387 and it has been pulled in. Close it for now.

Ref:
http://xpdacq.github.io/usb_Running.html#import-sample
