### ISSUE TITLE
don't let two versions of collection to be running at the same time

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#374]
or if that is too hard, don't let calls to RE/xrun to go at the same time.

**Comment by CJ-Wright** [comment]
We could set a global environmental variable, maybe? But it would be difficult to clear that on exit. We could set it upon xrun and then un-set upon xrun finishing. This wouldn't stop other computers from trying though. To do that we would need to move from an env var to a full on lock file on a beamline wide file system.

**Comment by sbillinge** [comment]
Let's try and solve this when it becomes an issue.  So far, nothing bad has happened as a result of this.  If it were a quick fix, I would do it, but bleh.
