### ISSUE TITLE
Recovering data

### ISSUE THREAD

**Issue by sbanerjee23** [xpdAcq/xpdAcq#392]
If a user does not run `integrate_and_save_last()` following a measurement and they leave the facility, how can the user recover that data? Are there any plans for how to resolve this in the near future within the constraints of what the facility allows? Is it possible to consider a solution where, at minimum, integrated data are automatically written to disk following an `xrun()`, which would be contingent on users properly calibrating the experimental geometry? Do you have any other suggestions?

**Comment by chiahaoliu** [comment]
see [xpdAn function](https://github.com/xpdAcq/xpdAn/blob/master/xpdan/callbacks_core.py)

**Comment by sbanerjee23** [comment]
Got it, thanks, will use a `run_and_save()` function next time
