### ISSUE TITLE
ENH: improve end_beamtime

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#399]
As reported, ``_end_beamtime`` might take a long time if there were large amounts of images collected. If the previous user didn't run ``end_beamtime`` ahead of time, that might cause a delay for the next user. 

Current approach: 
    Bundle (but not compress) ``xpdUser`` to remote backup place
Bottleneck:
    The network speed between local workstation at XPD and the remote storage managed by NSLS-II.

Proposed solution:
    1. Since new beamtime generally starts with a fresh terminal and new user usually has less interest in the old beamtime, we can use the fact and instruct the user to run ``end_beamtime`` at a different terminal.  Therefore, this ``end_beatime`` can take indefinitely long time and the system dialogue about archiving wouldn't bother the new user.
    2. Exclude tiffs while archiving to avoid network issue and provide a tool for beamline staff to recover all the tiffs collected within certain beamtime.

Add-on:
   Progress bar. This can assure the user that program is still working.
   ref: https://pypi.python.org/pypi/progressbar2/3.20.0

**Comment by CJ-Wright** [comment]
this might also work for a progress bar
https://pypi.python.org/pypi/tqdm

**Comment by CJ-Wright** [comment]
Maybe we can just do a subprocess call to `rsync`?
