### ISSUE TITLE
validate scan objects at instantiation time

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#40]
make sure that scan objects can run a scan at instantiation time, don't wait until the user tries to run it without success!  No need to do this for bluesky plan passthrough initially (though would be nice to in the long run)

**Comment by chiahaoliu** [comment]
I can only think of performing validation by passing it to a testRE (data won't be written to filestore) and abort it immediately after a scan is successfully run. That is definitely a terrible idea. @tacaswell, is there a logic in bluesky that can verify if a scan plan has required motor, detector and other scan parameters?
Thanks!

**Comment by tacaswell** [comment]
If you are using `PlanBase` and it's sub-classes you can introspect the value of dets, motors, etc.

**Comment by sbillinge** [comment]
most of the objects will be instantiated in the simulator, so I don't need any bluesky functionality.  I just want to make sure that the scanParams are valid.  e.g., if it is a scan 'ct' it needs 'exposure' key in the scanparm dict. and that should be a float or an int. value.

It would be good to have a separate validator because we could call it from prun, dark, but then call it too in __init__ of the scan object

I am not sure if it is better for it to be a bound method in Beamtime class or a separate function. Probably doesn't matter that much.

S

**Comment by sbillinge** [comment]
done.  Closing.
