### ISSUE TITLE
ENH: store long term beamline config

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#402]
It might be nice to put long term beamline configuration (which beamstop holder is used, the motors, etc) in a file which xpdAcq puts into the metadata. This will be good to make certain that the beamline config is the same when comparing data.

**Comment by CJ-Wright** [comment]
Maybe this goes under https://github.com/NSLS-II-XPD/ipython_ophyd?

**Comment by CJ-Wright** [comment]
@sbillinge thoughts?

**Comment by CJ-Wright** [comment]
@sghose?

**Comment by chiahaoliu** [comment]
Ideally we may want to pull information from ``olog`` but before this is feasible, we would need beamline support on providing required information at the first place and updating if any changes at the beamline for this functionality to work.
