### ISSUE TITLE
BUG: `save_last_tiff` does not record count time or other scan plan info

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#426]
`save_last_tiff` does not record count time or other scan plan info in the filename.

**Comment by chiahaoliu** [comment]
should we move this to ``xpdAn`` where ``save_last_tiff`` currently lives?

**Comment by CJ-Wright** [comment]
Yes, sorry

**Comment by CJ-Wright** [comment]
Issue moved to [xpdAcq/xpdAn #158](https://github.com/xpdAcq/xpdAn/issues/158) via [**ZenHub**](https://www.zenhub.com/)
