### ISSUE TITLE
BUG: shutter doesn't close after halting xrun

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#435]
### BUG:
Halting an xrun scan does not close the shutter.

### Reason for bug:
When the `RunEngine` (and by proxy `xrun`) are [halted](http://nsls-ii.github.io/bluesky/state-machine.html#halt) as opposed to [aborted](http://nsls-ii.github.io/bluesky/state-machine.html#abort) all things stop immediately with no cleanup what so ever. This means that the shutter will be in whatever position it was in.

### Potential Solution:
The halting feature of the system is working as intended, so I would file this under feature not bug.
To follow up on this we can:
1. Document this behavior (link to `RunEngine` interruptions page?)
1. Double check that the shutter closes at the end of all scans. This way if the `xrun` is aborted or stopped the shutter will be closed during cleanup. This will require that the users use abort/stop rather than halt.

**Comment by chiahaoliu** [comment]
Thanks for reporting  and in fact, we have covered both of the potential solutions listed above.

For the documentation about interrupting the scan, we have included here, along with ``bluesky`` official doc [reference here](https://xpdacq.github.io/xpdAcq/quickstart.html#interrupt-your-scan)

From the code side,  ``xrun`` is equipped with a finalizer that always closes shutter after plan [reference here](https://github.com/xpdAcq/xpdAcq/blob/master/xpdacq/xpdacq.py#L468). 

I would close this issue as aforementioned reasons.
