### ISSUE TITLE
ENH: make long term beamline config more proactive

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#438]
In an attempt to capture more metadata about the beamline config we should prompt BLS to change anything if needed
- [x] Put long term beamline config into start_beamtime function
- [x] Capture BLS initials when running start_beamtime
- [x] Print current config to screen (using `pprint` please)
- [x] Ask BLS to look it over and confirm config is correct.
- [x] If not correct pop up editor with config, then save and print/prompt again
- [x] if 'yes' continue with beamtime setup and save validated by information into config
- [ ] do one final load of config (with the validation info)

**Comment by chiahaoliu** [comment]
just a quick note.

beamline config is currently loaded in ipython profile in order to link it to ``xrun`` instance in a persistent way. Program raises ``xpdAcqException`` and inform user to load it if not exists).  [reference](https://github.com/xpdAcq/xpdAcq/blob/master/xpdacq/999-load.py#L61)

Linking to ``bt`` can reach the same goal as ``bt`` is always linked to ``xrun``

**Comment by CJ-Wright** [comment]
If you want we can do this all in the ipython setup. Just so long as we prompt people to verify it.

**Comment by chiahaoliu** [comment]
I think validating inside the program is a better approach. It's less scary than failing while loading.

Regarding the workflow stated above, I have a question:

Put long term beamline config into start_beamtime function --> are we going to handle the case of multiple configs?

**Comment by CJ-Wright** [comment]
I meant the loading of the beamline config. I guess we could chan map them together? But I don't know if we will run into the use case where we will want multiple configs.

**Comment by chiahaoliu** [comment]
Got you. Then the "capture the config" can be thought as ``pprint`` and interactive user input.
  
I agree the case of multiple beamline configs might be less likely.

**Comment by CJ-Wright** [comment]
yea, we may be able to put a subprocess call to the default editor for the actual editing of the config.

**Comment by eaculb** [comment]
I did not do a final re-load as the dict to be returned has the most up-to-date information including validation. The yaml file is rewritten with the final validation info.

**Comment by CJ-Wright** [comment]
No reloading the dict is fine.
