### ISSUE TITLE
create (analysis) environment and ianalysis on XPD

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#48]
This environment will be (currently) IDENTICAL to the collection environment except it will be called analysis so the terminal looks like:
(analysis) some/thing/here/xpdUser>

instead of
(collection) some/thing/here/xpdUser>

The user workflow will be to have a (collection) terminal open by typing icollection and then open an (analysis) terminal by typing ianalysis to do databroker stuff etc.

later they could load different things and be different from each other, but for now I think it is easier to make them start everything the same.

**Comment by chiahaoliu** [comment]
There is already an `analysis` environment at xpd computer, however most of packages are not up-to-date. I don't have write/update privilege on *this* conda environment but I can still clone this environment and create our own, such as `xpdAnalysis`

Do we want to create `xpdAnalysis` or do we want to kindly ask software team to update this environment ?

**Comment by danielballan** [comment]
Updating the analysis environments around the facility are on my to-do list for tomorrow. With all the focus on ophyd, basic housekeeping on JupyterHub has fallen behind.

**Comment by sbillinge** [comment]
just to be clear, what is this analysis env?  Is it the same as collect, or
how is it different (when it is updated)?

On Tue, Feb 9, 2016 at 10:38 PM, Dan Allan <notifications@github.com> wrote:

> Updating the analysis environments around the facility are on my to-do
> list for tomorrow. With all the focus on ophyd, basic housekeeping on
> JupyterHub has fallen behind.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/48#issuecomment-182183782>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by tacaswell** [comment]
Basically the same, but with out ophyd/pyepics installed so you _can not_ accidentally screw with the beamline.

**Comment by sbillinge** [comment]
perfect!  Exactly what we are looking for.  Now where is that smiley face emoticon?????

**Comment by CJ-Wright** [comment]
Closed, moved to repo mentioned above
