### ISSUE TITLE
ENH: separate beamline specific code

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#482]
As a wrapper on top of ``bluesky``,  we would expect the code in ``xpdAcq`` to be transferrable between beamlines. Most of code follows this fashion but there is still device-related code that is tied to beamline.

Suggested solution: 

Separate device-related code in ``xpdAcq`` and put it to a centralized module for the ease of maintaining.

**Comment by CJ-Wright** [comment]
I think this is done now.
