### ISSUE TITLE
shutil packages doesn't seem to work well for large data (~18G)

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#54]
`shutil` package, the one we used in `export_data()`, doesn't seem to work well for large data. It takes a long time (~5mins) and sometimes it just stops there... 

It functions well on cleaning existing file

**Comment by chiahaoliu** [comment]
Sorry, have to correct myself, I got a lot of numbers wrong....

Here is the correct version:

data on local drive : 17.8 G
data after compression : 7.8 G
Time needed to compress : ~9 mins

Packages works, just pretty slow. Freezing error comes from not enough space on local drive

**Comment by sbillinge** [comment]
yup, gotta get rid of those tiff files!  :)

On Fri, Feb 12, 2016 at 12:49 PM, Timothy Liu <notifications@github.com>
wrote:

> Sorry, have to correct myself, I got a lot of numbers wrong....
>
> Here is the correct version:
>
> data on local drive : 17.8 G
> data after compression : 7.8 G
> Time needed to compress : ~9 mins
>
> Packages works, just pretty slow. Freezing error comes from not enough
> space on local drive
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/54#issuecomment-183427736>.
>



-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by sbanerjee23** [comment]
@chiahaoliu This seems to be a known performance problem with shutil.make_archive(), which is being used in xpdacq.beamtime. 

Temporarily, have you considered testing the time needed to archive with the `tarfile` module instead?

- https://docs.python.org/2/library/archiving.html
- https://docs.python.org/2/library/tarfile.html

**Comment by chiahaoliu** [comment]
Closed. Confirm that is reasonable behavior and plus we are getting off tiff files now.

**Comment by sbillinge** [comment]
The behavior I want here is to do one complete export during the _end_beamtime() sequence, but not to offer this kind of exporting option to the user.  We will give them more granular ways of getting their data out.
