### ISSUE TITLE
PyYAML 5 breakage

### ISSUE THREAD

**Issue by CJ-Wright** [xpdAcq/xpdAcq#543]
It seems that PyYAML 5 causes breakage for us?

**Comment by CJ-Wright** [comment]
Also look at https://github.com/facebookresearch/Detectron/issues/840#issuecomment-478301208
We need to fix this, esp for windows users.

**Comment by chiahaoliu** [comment]
`safe_load` might be the solution from official doc.

https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
