### ISSUE TITLE
Need better logic in beamtimesetup

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#55]
Now we all rely on `_start_beamtime` to set up stem of all data paths, so `export_data` doesn't work in a ipython session that `_start_beamtime` hasn't been run which could be a very common situation.

**Comment by sbillinge** [comment]
Not really.   If people want to use xpdAcq then _start_beamtime must be
run.  If they don't want to use xpdAcq they don't have to, but then they
can't expect parts of it to work.  All of bluesky still works, but we don't
have to support that.

S

On Fri, Feb 12, 2016 at 12:42 PM, Timothy Liu <notifications@github.com>
wrote:

> Now we all rely on _start_beamtime to set up stem of all data paths, so
> export_data doesn't work in a ipython session that _start_beamtime hasn't
> been run which could be a very common situation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/55>.
>



-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
:+1:

**Comment by chiahaoliu** [comment]
add a `config.py` file in `startup/` and import specific parameter (like B_DIR) from there might solve our incorrect `B_DIR` puzzle yesterday. And this allows simulators and really XPD to work

**Comment by sbillinge** [comment]
Awesome.  I am still stuck on this.  Can you try it!

We also need to have a bt object available for some things to load.  I was
thinking to construct it, load, then deconstruct.

On Saturday, February 13, 2016, Timothy Liu <notifications@github.com>
wrote:

> add a config.py file in startup/ and import specific parameter (like
> B_DIR) from there might solve our incorrect B_DIR puzzle yesterday. And
> this allows simulators and really XPD to work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/55#issuecomment-183766204>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
This should be fixed by `glbl.py` but will close it after test at XPD

**Comment by chiahaoliu** [comment]
This issue has been solved with `glbl` approach and tested at XPD. Close.
