### ISSUE TITLE
tiff file naming scheme

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#58]
after conversations with Milinda and Sanjjit:

``>tif_base>ex_name>sa_name> filename.tiff``

filename:
* Tramp => ``<sc_name>_<temp>_<event_timestamp>_<event_uidshort>.tiff``
* Count => ``<sc_name>_ct<exp_time>_<event_timestamp>_<event_uidshort>.tiff``
* tseries=> ``<sc_name>_<event_timestamp>_<event_uidshort>.tiff``

**Comment by chiahaoliu** [comment]
Current naming scheme is more updated but slightly different from format mentioned here. Instrument scientist and our users seem happy with current naming. Can we close it?

**Comment by chiahaoliu** [comment]
close.
