### ISSUE TITLE
new decorator setter for beamtime attributes

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#6]
want the setter to write to yaml and the getter to read from yaml

**Comment by sbillinge** [comment]
moving to later milestone.  I would still like it if we could store pointers to yml files and read them when the object is used, rather than storing the information in a static form on instantiation. 

However, this is a somewhat lower priority than some other things.

**Comment by sbillinge** [comment]
close if ymls are read at runtime (or some other serialization method)

**Comment by chiahaoliu** [comment]
yes, yml files are now lively updated
