### ISSUE TITLE
automated dark subtraction

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#65]
1. ``dark(SamO,ScanO)`` is a run with the shutter closed where ``isdark=True`` is set  
 1.  users can run ``dark()`` manually and we won't change that.
 1. However, we seek an automated dark protocol that will look like the following:
    1. User requests a ``prun(SamO,ScanO)``
    1. Program gets ``ScanO.md.['sc_exposure']`` as ``exp``
    1. Program checks a list of available darks to see if one exists with that value of ``exp`` that was collected within ``expiration_range`` of time from now.  Not sure best way to generate this list.
    1. If it finds an existing dark that fits the bill, it retrieves its ``event_uid`` and stores it as ``'xp_dark_uid':uid_here`` in the xp metadata.   Even better, store a list of uids of all the darks that pass the test.
  1. That's it at collection time.  But at analysis time this happens:
    1. User types, for example, ``analyze(an.get(4))``.  Default is ``dark_subtract=True`` but can be overridden. 
    1. Program retrieves ``'xp_dark_uid'`` from ``an.get(4)``
    1. Program uses databroker to get the ``an.get(4)`` and the dark images from fileStore.
    1. Program takes the difference between the images.
    1. Program propagates the image to analysis stream (right now this would be a tiff-save)

**Comment by chiahaoliu** [comment]
After discussion with Dan and Tom, I realized software team already developed a platform for doing things we want. 

Here is the current functionality they have:
  - After an event, there will be two uids stored in header. One is related to the uid of light image (should probably be the same as this event uid) and another one is the uid of dark image which will be used in dark subtraction.
  - The logic of deciding which dark uid to be included in a header is completely customizable. We can fully apply our selection logic mentioned before.

In this sense, we we have both raw image and dark image in one header. (dark image is represented by an uid to dark event, so we won't waste storage place in nsls2) and the dark uid assignation is done at detector level, which is very robust.

When we do `save(an.get(index))`, we can easily do subtraction and return processed image back to user. Does this sound like a good idea?

Tom also guaranteed me a complete help on implementing this feature, if we make a reservation ahead our next visit.

**Comment by sbillinge** [comment]
yes, this is exactly the behavior I was going to use.  We will still need
the logic for finding that dark uid, but I don't mind if we store it in the
bluesky place or our own, which is what I was going to do.

S

On Wed, Feb 17, 2016 at 5:39 PM, Timothy Liu <notifications@github.com>
wrote:

> After discussion with Dan and Tom, I realized software team already
> developed a platform for doing things we want.
>
> Here is the current functionality they have:
>
>    - After an event, there will be two uids stored in header. One is
>    related to the uid of light image (should probably be the same as this
>    event uid) and another one is the uid of dark image which will be used in
>    dark subtraction.
>    - The logic of deciding which dark uid to be included in a header is
>    completely customizable. We can fully apply our selection logic mentioned
>    before.
>
> In this sense, we we have both raw image and dark image in one header.
> (dark image is represented by an uid to dark event, so we won't waste
> storage place in nsls2) and the dark uid assignation is done at detector
> level, which is very robust.
>
> When we do save(an.get(index)), we can easily do subtraction and return
> processed image back to user. Does this sound like a good idea?
>
> Tom also guaranteed me a complete help on implementing this feature, if we
> make a reservation ahead our next visit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/65#issuecomment-185441258>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by tacaswell** [comment]
To summarize:

 1. at analysis time need programmatic access to dark image associated with a given light image
 2. we need some way to at collection time associate each light image with a dark image

**Comment by sbillinge** [comment]
Yup, that's it.

On Monday, February 22, 2016, Thomas A Caswell <notifications@github.com>
wrote:

> To summarize:
>
>    1. at analysis time need programmatic access to dark image associated
>    with a given light image
>    2. we need some way to at collection time associate each light image
>    with a dark image
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/65#issuecomment-187171661>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by tacaswell** [comment]
I think adding a 

```python
dark_image = Cpt(Signal, None)
```

to the detector and then

```python
def collect_dark_frame():
    close_shutter()
    pe1c.stage()
    st = pe1c.trigger()
    while not st.done:
        ttime.sleep(.1)
    df = pe1c.read()
    pe1c.dark_frame.put(**df)
```

**Comment by tacaswell** [comment]
or something close to that modulo grave typos and a missing unstage.

**Comment by chiahaoliu** [comment]
close after testing at XPD.
