### ISSUE TITLE
save calibration data with ``xp`` metadata

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#66]
workflow is:

1. User runs ``calibration(sampleO,scanO)``
2. Calibration runs a prun but sets ``'iscalibration'=True``
3. in ``(analysis)`` User runs ``an.list('cal')`` which filters for ``iscalibration=T``
4. User runs ``calibrate(an.get(3))``
4. ``calibrate`` gets the image data from ``an.get(3)``, does a dark subtraction if possible and passes the image to ``tiff_base/calibrations`` 
1. User goes to xPDFsuite, opens the calibration data and does the calibration.
1. User saves the ``calibration.config`` file in ``config_base`` with some reasonable name. Use the logic we came up with before?

The above can be implemented later, but as long as there is a calibration file saved in ``config_base``, however it got there
  1. User requests a ``prun()`` 
  1. ``prun`` looks for a calibration file in ``config_base`` and tries to find the most recent one.
  1. the config file is parsed and the calibration information saved as metadata by prun in ``'xp_calibration':{keys:values}`` metadata (not sure the exact syntax but we an reuse what we had before).

**Comment by chiahaoliu** [comment]
Tested at XPD. Calibration information is loaded automatically and confirmed those parameters are recorded properly in header pull from `databroker`. Close for now.
