### ISSUE TITLE
fix tscan logic

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#67]
from Eric's email:

 
Starting_T           ending_T             requested T_step            computed T_step
200         180         5              6.3333
500         300         100         -200
100         500         100         133.33
etc

we are not handling the edge-cases properly.

**Comment by sbillinge** [comment]
I have fixed this and pushed so it should be in the latest pull-request.  

It needs to be tested before closing this.

S

**Comment by chiahaoliu** [comment]
I just tested this problem and here is the solution I proposed:
```
def _nsteps(startingT, endingT, step_size):
    # create an array with desired step_size and we need to take negative sign
    if (endingT-startingT) > 0:
        _step_size = abs(step_size)  # abs to avoid any confusion
    elif (endingT - startingT) < 0:
        _step_size = -abs(step_size)
    desired_space_array = np.arange(startingT, endingT, _step_size)
    computed_nstep = len(desired_space_array) +1
    computed_array = np.linspace(startingT, endingT, computed_nstep)  # that's what bluesky takes
    computed_step_size = computed_array[-1] - computed_array[-2]   # avoid array with single step, probably less likely to happen but to be safe
    print('INFO: requested temperature step size = ',step_size,' -> computed temperature step size:',abs(computed_step_s)
    ize)
    return computed_nstep
```
and the tests I got were:
```
200 180 5  --> array([ 200.,  195.,  190.,  185.,  180.])
500 300 100 --> array([ 500.,  400.,  300.])
100 500 100 --> array([ 100.,  200.,  300.,  400.,  500.])
80 90 1.5 --> array([ 80.        ,  81.42857143,  82.85714286,  84.28571429,
        85.71428571,  87.14285714,  88.57142857,  90.        ])
```

Does it look good?

**Comment by sbillinge** [comment]
I already fixed it.  It just needs a +1 after the int(req_nsyeps).  It is
in my last commit on the PR

On Saturday, February 13, 2016, Timothy Liu <notifications@github.com>
wrote:

> I just tested this problem and here is the solution I proposed:
>
> def _nsteps(startingT, endingT, step_size):
>     # create an array with desired step_size and we need to take negative sign
>     if (endingT-startingT) > 0:
>         _step_size = abs(step_size)  # abs to avoid any confusion
>     elif (endingT - startingT) < 0:
>         _step_size = -abs(step_size)
>     desired_space_array = np.arange(startingT, endingT, _step_size)
>     computed_nstep = len(desired_space_array) +1
>     computed_array = np.linspace(startingT, endingT, computed_nstep)  # that's what bluesky takes
>     computed_step_size = computed_array[-1] - computed_array[-2]   # avoid array with single step, probably less likely to happen but to be safe
>     print('INFO: requested temperature step size = ',step_size,' -> computed temperature step size:',abs(computed_step_s)
>     ize)
>     return computed_nstep
>
> and the tests I got were:
>
> 200 180 5  --> array([ 200.,  195.,  190.,  185.,  180.])
> 500 300 100 --> array([ 500.,  400.,  300.])
> 100 500 100 --> array([ 100.,  200.,  300.,  400.,  500.])
> 80 90 1.5 --> array([ 80.        ,  81.42857143,  82.85714286,  84.28571429,
>         85.71428571,  87.14285714,  88.57142857,  90.        ])
>
> Does it look good?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/67#issuecomment-183713697>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by sbillinge** [comment]
Oh, I see...we also have to handle whether T is going up or down? Or
bluesky handles that correctly given start and stopT?

On Saturday, February 13, 2016, Simon Billinge <simon.billinge@gmail.com>
wrote:

> I already fixed it.  It just needs a +1 after the int(req_nsyeps).  It is
> in my last commit on the PR
>
> On Saturday, February 13, 2016, Timothy Liu <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I just tested this problem and here is the solution I proposed:
>>
>> def _nsteps(startingT, endingT, step_size):
>>     # create an array with desired step_size and we need to take negative sign
>>     if (endingT-startingT) > 0:
>>         _step_size = abs(step_size)  # abs to avoid any confusion
>>     elif (endingT - startingT) < 0:
>>         _step_size = -abs(step_size)
>>     desired_space_array = np.arange(startingT, endingT, _step_size)
>>     computed_nstep = len(desired_space_array) +1
>>     computed_array = np.linspace(startingT, endingT, computed_nstep)  # that's what bluesky takes
>>     computed_step_size = computed_array[-1] - computed_array[-2]   # avoid array with single step, probably less likely to happen but to be safe
>>     print('INFO: requested temperature step size = ',step_size,' -> computed temperature step size:',abs(computed_step_s)
>>     ize)
>>     return computed_nstep
>>
>> and the tests I got were:
>>
>> 200 180 5  --> array([ 200.,  195.,  190.,  185.,  180.])
>> 500 300 100 --> array([ 500.,  400.,  300.])
>> 100 500 100 --> array([ 100.,  200.,  300.,  400.,  500.])
>> 80 90 1.5 --> array([ 80.        ,  81.42857143,  82.85714286,  84.28571429,
>>         85.71428571,  87.14285714,  88.57142857,  90.        ])
>>
>> Does it look good?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xpdAcq/xpdAcq/issues/67#issuecomment-183713697>.
>>
>
>
> --
> Prof. Simon Billinge
> Applied Physics & Applied Mathematics
> Columbia University
> 500 West 120th Street
> Room 200 Mudd, MC 4701
> New York, NY 10027
> Tel: (212)-854-2918 (o) 851-7428 (lab)
>
> Condensed Matter Physics and Materials Science Dept.
> Brookhaven National Laboratory
> P.O. Box 5000
> Upton, NY 11973-5000
> (631)-344-5661
>
> email: sb2896 at columbia dot edu
> home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/
>
>

-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
bluesky takes startingT, endingT and steps. It does take care of increasing or decreasing.

I tested your method and and the one I proposed above, here are the results:
```
200 180 5 case
int+1 mehtod  --> array([ 200.,  195.,  190.,  185.,  180.])  correct
my method --> array([ 200.,  195.,  190.,  185.,  180.]) correct

200 180 2.7 case ( weird, but test stability)
int+1 method --> array([ 180.        ,  182.85714286,  185.71428571,  188.57142857,
        191.42857143,  194.28571429,  197.14285714,  200.        ])   #each step become wilder
my method --> array([ 180. ,  182.5,  185. ,  187.5,  190. ,  192.5,  195. ,  197.5,
        200. ])  #each step is samller
```

From what I heard from users, they don't mind a slightly finer grid but they are less comfortable with larger step then expected.

**Comment by sbillinge** [comment]
I think they should give the same result with the ``abs()`` in there, no?

S

On Sat, Feb 13, 2016 at 1:54 PM, Timothy Liu <notifications@github.com>
wrote:

> bluesky takes startingT, endingT and steps. It does take care of
> increasing or decreasing.
>
> I tested your method and and the one I proposed above, here are the
> results:
>
> 200 180 5 case
> int+1 mehtod  --> array([ 200.,  195.,  190.,  185.,  180.])  correct
> my method --> array([ 200.,  195.,  190.,  185.,  180.]) correct
>
> 200 180 2.7 case ( weird, but test stability)
> int+1 method --> array([ 180.        ,  182.85714286,  185.71428571,  188.57142857,
>         191.42857143,  194.28571429,  197.14285714,  200.        ])   #each step become wilder
> my method --> array([ 180. ,  182.5,  185. ,  187.5,  190. ,  192.5,  195. ,  197.5,
>         200. ])  #each step is samller
>
> From what I heard from users, they don't mind a slightly finer grid but
> they are less comfortable with larger step then expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/67#issuecomment-183723061>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
According to Eric's request in email.

It takes some time to deal with `+=` problem in python and I know this code is not neat....

```
def convertT (startT, endT, step_size):
    if startT > endT:
        _step_size = -(step_size)
    else: 
        _step_size = (step_size)  
    # cause python always think `+=` is increasing, even you give a negative number

    return _cal_T(startT, endT, step_size)

def _cal_T(startT, endT, step_size):
    import numpy as np
    cal_endT = startT
    nsteps = 0
    
    while True:
        cal_endT += step_size
        nsteps += 1
        if step_size>0:
            if cal_endT > endT:
                break
        if step_size<0:
            if cal_endT < endT:
                break
    computed_Tarray = np.linspace(startT, cal_endT, nsteps+2)
    # two steps comes from 1) similar reason as int+1 2) extra step
    
    print('Computed steps in Tseries will be ===>\n%s' % computed_Tarray)
    print('\nwith %s steps' % str(nsteps+2))
    # this will be what bluesky takes

    return (startT, cal_endT, nsteps+2)
```

This code is more risky than `int+1` fix, but I think I can deal with it. Is the print statement here redundant or comforting?

**Comment by tacaswell** [comment]
I think

```python
n_steps = 1 + ((endT - startT) // step_size)
computed_start, computed_stop = startT, startT + n_steps + step_size
```

will do what you want.

**Comment by tacaswell** [comment]
sorry, typo in first post (edited to fix)

```python
computed_start, computed_stop = startT, startT + n_steps * step_size
```

**Comment by tacaswell** [comment]
and you might need an extra abs call.

**Comment by chiahaoliu** [comment]
Thanks Tom. That was close to what I thought at first but this approach actually gives error when dealing with large step.

Like startT, endT, step =(100, 200, 100)
Will give [100, 300] array(yup, I need np.linspace as output)

**Comment by tacaswell** [comment]
The other solution to this is not not accept the step size as an argument, but make users provide the _number_ of steps, that way they can not provide you with inconsistent inputs.

See  https://github.com/scikit-beam/scikit-beam/blob/master/skbeam/core/utils.py#L725 for a complete handling of generating bin edges.

**Comment by chiahaoliu** [comment]
Taking step size as an argument would be the ultimate solution, but unfortunately user usually don't like to calculate how many steps they want, they only want to specify step_size...

`bin_edges` is very helpful, I might use it as the backend. Thanks!

**Comment by sbillinge** [comment]
I think this is done.  @chiahaoliu, is it tested and pushed?  If so, please could you close this issue, which will close out the first Milestone.

Great job guys!

**Comment by chiahaoliu** [comment]
yes, this is done!
