### ISSUE TITLE
more feedback to user during temperature scans

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#70]
This from Eric,

Another useful feature (that is not needed for now) would be to have some comments appear on the screen as the T series scan progresses. Right now, I do not know how far the scan is. I can guess though, by looking on the other screen the cryostream CSstudio window. But it would be good to track the sequential scans as they get executed. Also is there a way each command can be shown (live and in history) with time of execution. It would help tracks things vs. time and make better informed decision on subsequent scans. Again, not a showstopper.
E

**Comment by tacaswell** [comment]
A `LiveTable` is not being used?

**Comment by sbillinge** [comment]
We pass a livetable=True by default, which is supposed to set that sub so
we just have to look see if there is a bug or logic missing in our code.
Some of this stuff was put together in a hurry ;)

On Saturday, February 13, 2016, Thomas A Caswell <notifications@github.com>
wrote:

> A LiveTable is not being used?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/70#issuecomment-183766019>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
I admit I broke it for sure ... :p

**Comment by sbillinge** [comment]
No worries.  I threw up the issue and we will get to them in good time.

S

On Saturday, February 13, 2016, Timothy Liu <notifications@github.com>
wrote:

> I admit I broke it for sure ... :p
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/70#issuecomment-183811073>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
I just fixed it with Milinda. 

Actually that is something more subtle: `scan.sc_params` only gives `exposure time` and other user defined scan parameters. However `scan.md` does show `subs` is under `sc_params` dictionary.

I am looking at codes and try to figure out the root to this problem.

**Comment by chiahaoliu** [comment]
This should be fixed by always using `obj.md['key']`. Codes related to this are cleaned but will confirm it after testing at XPD computer.

**Comment by sbillinge** [comment]
@chiahaoliu can this be closed?  Please test to make sure then close

**Comment by chiahaoliu** [comment]
Yes, this has been sorted out. It resulted from that fields in `ScanPlan.md` are not necessary defined during instantiation, some of them are added in during `get_light_image` or `_unpack_and_run`. Close.
