### ISSUE TITLE
bt.list is immutable 

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#71]
items never change their position in the list

**Comment by chiahaoliu** [comment]
a light-weight approach of doing this may be putting `sorted` function into `loadyaml`, right after `os.listdir`, so that every time `bt.list` return an ordered list.

reference:
[https://wiki.python.org/moin/HowTo/Sorting]

**Comment by sbillinge** [comment]
I am working on this issue.

On Tuesday, February 23, 2016, Timothy Liu <notifications@github.com> wrote:

> a light-weight approach of doing this may be putting sorted function into
> loadyaml, right after os.listdir, so that every time bt.list return an
> ordered list.
>
> reference:
> [https://wiki.python.org/moin/HowTo/Sorting]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/71#issuecomment-187817387>.
>


-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
solved in the most updated version.
