### ISSUE TITLE
Take a look at ChainedMap

### ISSUE THREAD

**Issue by danielballan** [xpdAcq/xpdAcq#73]
Take a look at the example `DeepChainedMap`. As of Python 3.3, the core language gives a nice way to merge dictionaries that come from different sources. I just discovered this this morning or I would have suggested in earlier.

https://docs.python.org/3.5/library/collections.html#chainmap-examples-and-recipes

**Comment by sbillinge** [comment]
wow, that looks pretty cool.

On Mon, Feb 15, 2016 at 9:42 AM, Dan Allan <notifications@github.com> wrote:

> Take a look at the example DeepChainedMap. As of Python 3.3, the core
> language gives a nice way to merge dictionaries that come from different
> sources. I just discovered this this morning or I would have suggested in
> earlier.
>
>
> https://docs.python.org/3.5/library/collections.html#chainmap-examples-and-recipes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/73>.
>



-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
Look a little bit deep, but I am trying to understand it...

**Comment by sbillinge** [comment]
Though please don't spend too much time on it now....this is a "for later"
thing.

S

On Mon, Feb 15, 2016 at 11:25 AM, Timothy Liu <notifications@github.com>
wrote:

> Look a little bit deep, but I am trying to understand it...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/73#issuecomment-184280652>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
:+1:

**Comment by sbillinge** [comment]
Closing.
