### ISSUE TITLE
Find the best PV related to beam dump

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#75]
find the most suitable PV related to beam dump, and register our run engine. 

example code:
```
from bluesky.suspenders import PVSuspendFloor
PVSuspendFloor(RE, 'PV_HERE', 7.5e-9, resume_thresh=8.3e-9)
```

This should be under version control as well.

**Comment by sbillinge** [comment]
@chiahaoliu can we close this?

However we need a new issue that the suspender doesn't restart the beamtime.  Perhaps this new issue, and also the resume() bugfix can be done next week during  your time with Tom

**Comment by chiahaoliu** [comment]
Yes, we can close it. I found the PV for beam current and it seems to suspended properly in the past beamtimes. Close.

**Comment by sbillinge** [comment]
I thought those guys were saying that it didn't restart when the beam came back?

**Comment by chiahaoliu** [comment]
I suspect that had to do with `resume` or something more subtle because I played suspender with simple PV( flip between 0 or 1) with `RE(plan)` in command line and it worked fine at that time   Let me reopen it so that I will remember to test it.

**Comment by chiahaoliu** [comment]
xpdAcq works properly but there is actually internal error message from `bluesky` which might be a potential concern. I will create a bug report to `bluesky`.

**Comment by chiahaoliu** [comment]
Issue now lies in `bluesky` but further request should put into `bluesky`.
