### ISSUE TITLE
[bug] unkown issue to end_beamtime

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#78]
part of code is as following:
```
    ....
    shutil.rmtree(dp.base)
    os.makedirs(dp.base, exist_ok=True)
    shutil.copy(archive_f_name, dp.base)
    final_path = os.path.join(dp.base, os.path.basename(archive_f_name)) # local archive
    #print("Final archive file at {}".format(final_path))

    return 'local copy of tarball for user: '+final_path
```
return vale of `end_beamtime` poped out, but directories under `/xpdUser` were not flushed.

**Comment by chiahaoliu** [comment]
Test Result:
It works properly now. Still don't know the reason, might have to do data size under `/xpdUser`

**Comment by sbillinge** [comment]
the data compression takes a long time on the end_beamtime which still seems to be an issue.  consider saving the tar file without zipping it?

**Comment by chiahaoliu** [comment]
That was a bug long ago. Test at XPD with Sanjit today(2016/04/13) . `end_beamtime` went well. Close it now.
