### ISSUE TITLE
test Tramp

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#80]
test if code breaks after renaming Tseries to Tramp

**Comment by chiahaoliu** [comment]
verified. it is working.

**Comment by sbillinge** [comment]
whoo hooo :)

On Tue, Feb 16, 2016 at 11:46 AM, Timothy Liu <notifications@github.com>
wrote:

> Closed #80 <https://github.com/xpdAcq/xpdAcq/issues/80>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/80#event-552290483>.
>



-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com
