### ISSUE TITLE
maybe do incremental exports:

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#82]
using something like this:
https://pypi.python.org/pypi/incremental-backups-tools/0.1.0

This could be more agile.

We could also implement a Globus solution so people can ship files directly to their computers at home.  This should be done by the software group though.

**Comment by sbanerjee23** [comment]
:+1:

**Comment by sbanerjee23** [comment]
Or just instructions for using filestore if it's ready.

**Comment by chiahaoliu** [comment]
http://nsls-ii.github.io/databroker/searching.html

This gives an instruction on how to search `filestore`. Once you find the header you want, you can pass this header object as an argument (could be a list of header) to `save_tiff` then you will have local copy in tif_base

Basic searching functionality would be integrated into our package, but it is not there yet.

**Comment by sbanerjee23** [comment]
Thanks @chiahaoliu. Unfortunately this particular documentation isn't so helpful as a starting point for a general user (not your job, but):

- No links for where to download DataBroker package (or if that is necessary)
- No hint of where to set up a remote VPN connection (or if that is a necessary)
- No hint that we first need to set up a controls account (or if that is a necessary)

So, even when I am able to google around, and find a possible starting point: (http://nsls-ii.github.io/analysis-quick-start.html#option-2-remotely), my first step is to contact an NSLS II system admin...

But, not complaining, happy to wait until things are (more) ready.

**Comment by chiahaoliu** [comment]
No longer need this functionality. Close
