### ISSUE TITLE
[troubleshooting] Python confusion

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#84]
Note for myself:

if we want to switch from `python setup.py develop` to `python setup.py install` we need to run `pip uninstall <package_name>` under certain conda environment multiple times until we have `import error`.

By doing this, we ensure dependency in system is entirely removed so that python won't get confused with which version to load and use

**Comment by sbillinge** [comment]
can't we just make a new conda environment and delete the old one?

But perhaps your approach is better.   either way....good work.

S

On Wed, Feb 17, 2016 at 2:16 PM, Timothy Liu <notifications@github.com>
wrote:

> Note for myself:
>
> if we want to switch from python setup.py develop to python setup.py
> install we need to run pip uninstall <package_name> under certain conda
> environment multiple times until we have import error.
>
> By doing this, we ensure dependency in system is entirely removed so that
> python won't get confused with which version to load and use
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/84>.
>



-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
This is for beamline specifically cause we can't alter `collection` environment there

**Comment by sbillinge** [comment]
ok, no problem.  Use whatever works....

S

On Wed, Feb 17, 2016 at 4:20 PM, Timothy Liu <notifications@github.com>
wrote:

> This is for beamline specifically cause we can't alter collection
> environment there
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/84#issuecomment-185409956>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
Closed. Write this into my own notebook now.
