### ISSUE TITLE
directory naming is consistent

### ISSUE THREAD

**Issue by sbillinge** [xpdAcq/xpdAcq#86]
I would prefer the directory where everthing is spawned from to be called ``base`` (or ``base_dir`` or ``db.base``, ``B_DIR`` etc.), the the xpdUser directory that is put in there to be ``home`` (or ``home_dir`` or ``db.home``, etc.) and for this naming to be consistent through the project.  Right now I think it is ok except that I think ``db.base`` points to ``home`` and this will cause endless confusion as we move forward (in fact it already is).

We had something called ``stem`` which we can retire.

We can also talk about this naming scheme if there is a better way to name it.

**Comment by chiahaoliu** [comment]
This should be fixed using `glbl.py` structure but will test it after testing at XPD computer.

**Comment by chiahaoliu** [comment]
tested and verified at beamline.
