### ISSUE TITLE
[user_feedback] 2016.02.25

### ISSUE THREAD

**Issue by chiahaoliu** [xpdAcq/xpdAcq#96]
This feedback is related to in-situ measurement, with small overlap with feedback we had before. 

For advanced users, they might need a delicate scan plan that allows them to take dark at the largest degree of freedom. For example, if detector is somehow unstable and dark current changes a lot, then user would like to take dark current more frequently during the long scan. Ideally the timing of taking dark frames should be user configurable (and maybe interactively?)

Current problem is that we can't take dark frame during a long scan and data can't be retrieved from `databroker` util the scan is done. That's not a problem for short scans, but if that is a long scan, say like 4.5hrs, user would want to have a look at data that have been collected so far and he might also want to change timing of taking dark frame during scan.

**Comment by sbillinge** [comment]
Thanks for capturing this.  It is pretty much all possible now.  Is there
evidence that the dark current is unstable?

On Thursday, February 25, 2016, Timothy Liu <notifications@github.com>
wrote:

> This feedback is related to in-situ measurement, with small overlap with
> feedback we had before.
>
> For advanced users, they might need a delicate scan plan that allows them
> to take dark at the largest degree of freedom. For example, if detector is
> somehow unstable and dark current changes a lot, then user would like to
> take dark current more frequently during the long scan. Ideally the timing
> of taking dark frames should be user configurable (and maybe interactively?)
>
> Current problem is that we can't take dark frame during a long scan and
> data can't be retrieved from databroker util the scan is done. That's not
> a problem for short scans, but if that is a long scan, say like 4.5hrs,
> user would want to have a look at data that have been collected so far and
> he might also want to change timing of taking dark frame during scan.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/96>.
>


-- 
----
Prof. Simon Billinge

Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http://thebillingegroup.com

**Comment by chiahaoliu** [comment]
This guess was based on the fact that sawtooth pattern still exists in subtracted image, if dark frame was only taken at the beginning of a long scan. Above strategy worked for temperature scan weeks ago.

**Comment by sbillinge** [comment]
I see, thanks.

For now I don't know the status of the automated dark subtraction by
bluesky but to reiterate, here is the use-case we want, which satisfies
what the experimenters want.  We can implement this at our level and go
with bluesky later if it makes sense:

1) User selects a "sell-by-time".  This is the longest period of time that
they are comfortable between the dark collection time and the light
collection time.
2) User requests a run of some sort
3) Software checks a database (yaml file for now) of darks. If it finds a
"good" dark it sets the dark uid in metadata and moves on.  If it doesn't
find a good dark it collects a dark and saves the dark_uid in its
metadata.  The definition of a "good" dark is that the exposure time is the
same as that requested for the light, and that it is within the
sell-by-time.  If the sell-by-time is zero, or less than the exposure time,
collect a dark for every light.

For this to work at our level we will need our own tseries and Tramps
unless there is some kind of call-back that is offered on the detector.

I think there is more for us to find out about the darks and we can come up
with better behavior in the long run.

The workaround that can work for now is what the experimenters did before,
which was to make a script that interspersed dark() with shorter Tramps.

S

On Fri, Feb 26, 2016 at 12:52 AM, Timothy Liu <notifications@github.com>
wrote:

> This guess was based on the fact that sawtooth pattern still exists in
> subtracted image, if dark frame was only taken at the beginning of a long
> scan. Above strategy worked for temperature scan weeks ago.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xpdAcq/xpdAcq/issues/96#issuecomment-189123914>.
>



-- 
Prof. Simon Billinge
Applied Physics & Applied Mathematics
Columbia University
500 West 120th Street
Room 200 Mudd, MC 4701
New York, NY 10027
Tel: (212)-854-2918 (o) 851-7428 (lab)

Condensed Matter Physics and Materials Science Dept.
Brookhaven National Laboratory
P.O. Box 5000
Upton, NY 11973-5000
(631)-344-5661

email: sb2896 at columbia dot edu
home: http:// <http://nirt.pa.msu.edu/>bgsite.apam.columbia.edu/

**Comment by chiahaoliu** [comment]
I have been working on dark subtraction based on the workflow described above, but I already found there is a problem in the dark subtraction logic after yesterday: I treat every event in the unit of `prun`. So dark only gets checked per `prun` and that would be problematic if a `prun` is super long one.

I think to solve this problem completely, we can probably do two things: 1) Work on detector level. Adding dark subtraction logic coded by ourselves to area detector, so every time this logic is passed when we trigger the detector, i.e. take a light image.  2) work on bluesky scan level. Write up our own scan plan with `Msg` method. Our own scan will basically be the same as `Count` or `AbsScanPlan` in `bluesky`, the only difference is we insert our logic of finding a "good" dark every time before we trigger the detector, pseudo code might be:
```
def smart_scan(motro, det, light_cnt_time):
    yield Msg('open_run')
    for i in range(-5, 5):
        yield Msg('create')
        yield Msg('set', motor, i)
        _find_the_right_dark(light_cnt_time)  # our logic
        yield Msg('trigger', det)
        yield Msg('read', motor)
        yield Msg('read', det)
        yield Msg('save')
    yield Msg('close_run')
```

Those are two possible approach I can think of, there might be a better one.

**Comment by sbillinge** [comment]
Yes, this is understood.  I think the current status is:
1) tell users to make shorter pruns for now
2) have the same logic coded into the area_detector per conversations with Tom

I think I would avoid duplicating their AbsScan logic right now.

@tacaswell what is the status of getting our desired dark-scan behavior from at the area_detector level?  If it is quick we will wait, if it is low on the todo-list we will code up a workaround.

**Comment by tacaswell** [comment]
You can also embed this logic in `trigger` (assuming you can control the shutter) See https://github.com/NSLS-II/ophyd/blob/master/ophyd/areadetector/trigger_mixins.py#L86

In principle any sort of cache / time-to-live logic could also live there.

**Comment by sbillinge** [comment]
@chiahaoliu @tacaswell  let's talk about this.  Maybe we can implement it ourselves with a custom bluesky scan and we don't need to have a custom built-in area-detector solution.  But let's discuss it before we spend too much time on it.

**Comment by sbillinge** [comment]
Users seem happy with the current automated dark subtraction. @chiahaoliu please close this issue, but open a new issue to write good documentation on the automated dark sequence.
